import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { TeamTraderListRelationFilter } from "../teamTrader/TeamTraderListRelationFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type TeamWhereInput = {
  closed?: IntNullableFilter;
  dailyClosed?: IntNullableFilter;
  dailyPnl?: FloatNullableFilter;
  dailyRoe?: FloatNullableFilter;
  dailyWr?: FloatNullableFilter;
  id?: StringFilter;
  monthlyClosed?: IntNullableFilter;
  monthlyPnl?: FloatNullableFilter;
  monthlyRoe?: FloatNullableFilter;
  monthlyWr?: FloatNullableFilter;
  name?: StringNullableFilter;
  pnl?: FloatNullableFilter;
  roe?: FloatNullableFilter;
  spotClosed?: IntNullableFilter;
  spotDailyClosed?: IntNullableFilter;
  spotDailyPnl?: FloatNullableFilter;
  spotDailyRoe?: FloatNullableFilter;
  spotDailyWr?: FloatNullableFilter;
  spotMonthlyClosed?: IntNullableFilter;
  spotMonthlyPnl?: FloatNullableFilter;
  spotMonthlyRoe?: FloatNullableFilter;
  spotMonthlyWr?: FloatNullableFilter;
  spotPnl?: FloatNullableFilter;
  spotRoe?: FloatNullableFilter;
  spotWeeklyClosed?: IntNullableFilter;
  spotWeeklyPnl?: FloatNullableFilter;
  spotWeeklyRoe?: FloatNullableFilter;
  spotWeeklyWr?: FloatNullableFilter;
  spotWr?: FloatNullableFilter;
  statAt?: DateTimeNullableFilter;
  summaryDailyRoe?: FloatNullableFilter;
  summaryDailyWr?: FloatNullableFilter;
  summaryMonthlyRoe?: FloatNullableFilter;
  summaryMonthlyWr?: FloatNullableFilter;
  summaryRoe?: FloatNullableFilter;
  summaryWeeklyRoe?: FloatNullableFilter;
  summaryWeeklyWr?: FloatNullableFilter;
  summaryWr?: FloatNullableFilter;
  teamTraders?: TeamTraderListRelationFilter;
  user?: UserWhereUniqueInput;
  weeklyClosed?: IntNullableFilter;
  weeklyPnl?: FloatNullableFilter;
  weeklyRoe?: FloatNullableFilter;
  weeklyWr?: FloatNullableFilter;
  wr?: FloatNullableFilter;
};
