import { SortOrder } from "../../util/SortOrder";

export type TeamOrderByInput = {
  closed?: SortOrder;
  dailyClosed?: SortOrder;
  dailyPnl?: SortOrder;
  dailyRoe?: SortOrder;
  dailyWr?: SortOrder;
  id?: SortOrder;
  monthlyClosed?: SortOrder;
  monthlyPnl?: SortOrder;
  monthlyRoe?: SortOrder;
  monthlyWr?: SortOrder;
  name?: SortOrder;
  pnl?: SortOrder;
  roe?: SortOrder;
  spotClosed?: SortOrder;
  spotDailyClosed?: SortOrder;
  spotDailyPnl?: SortOrder;
  spotDailyRoe?: SortOrder;
  spotDailyWr?: SortOrder;
  spotMonthlyClosed?: SortOrder;
  spotMonthlyPnl?: SortOrder;
  spotMonthlyRoe?: SortOrder;
  spotMonthlyWr?: SortOrder;
  spotPnl?: SortOrder;
  spotRoe?: SortOrder;
  spotWeeklyClosed?: SortOrder;
  spotWeeklyPnl?: SortOrder;
  spotWeeklyRoe?: SortOrder;
  spotWeeklyWr?: SortOrder;
  spotWr?: SortOrder;
  statAt?: SortOrder;
  summaryDailyRoe?: SortOrder;
  summaryDailyWr?: SortOrder;
  summaryMonthlyRoe?: SortOrder;
  summaryMonthlyWr?: SortOrder;
  summaryRoe?: SortOrder;
  summaryWeeklyRoe?: SortOrder;
  summaryWeeklyWr?: SortOrder;
  summaryWr?: SortOrder;
  userId?: SortOrder;
  weeklyClosed?: SortOrder;
  weeklyPnl?: SortOrder;
  weeklyRoe?: SortOrder;
  weeklyWr?: SortOrder;
  wr?: SortOrder;
};
