import { TeamTraderUpdateManyWithoutTeamsInput } from "./TeamTraderUpdateManyWithoutTeamsInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type TeamUpdateInput = {
  closed?: number | null;
  dailyClosed?: number | null;
  dailyPnl?: number | null;
  dailyRoe?: number | null;
  dailyWr?: number | null;
  monthlyClosed?: number | null;
  monthlyPnl?: number | null;
  monthlyRoe?: number | null;
  monthlyWr?: number | null;
  name?: string | null;
  pnl?: number | null;
  roe?: number | null;
  spotClosed?: number | null;
  spotDailyClosed?: number | null;
  spotDailyPnl?: number | null;
  spotDailyRoe?: number | null;
  spotDailyWr?: number | null;
  spotMonthlyClosed?: number | null;
  spotMonthlyPnl?: number | null;
  spotMonthlyRoe?: number | null;
  spotMonthlyWr?: number | null;
  spotPnl?: number | null;
  spotRoe?: number | null;
  spotWeeklyClosed?: number | null;
  spotWeeklyPnl?: number | null;
  spotWeeklyRoe?: number | null;
  spotWeeklyWr?: number | null;
  spotWr?: number | null;
  statAt?: Date | null;
  summaryDailyRoe?: number | null;
  summaryDailyWr?: number | null;
  summaryMonthlyRoe?: number | null;
  summaryMonthlyWr?: number | null;
  summaryRoe?: number | null;
  summaryWeeklyRoe?: number | null;
  summaryWeeklyWr?: number | null;
  summaryWr?: number | null;
  teamTraders?: TeamTraderUpdateManyWithoutTeamsInput;
  user?: UserWhereUniqueInput;
  weeklyClosed?: number | null;
  weeklyPnl?: number | null;
  weeklyRoe?: number | null;
  weeklyWr?: number | null;
  wr?: number | null;
};
