/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClapService } from "../clap.service";
import { ClapCreateInput } from "./ClapCreateInput";
import { Clap } from "./Clap";
import { ClapFindManyArgs } from "./ClapFindManyArgs";
import { ClapWhereUniqueInput } from "./ClapWhereUniqueInput";
import { ClapUpdateInput } from "./ClapUpdateInput";

export class ClapControllerBase {
  constructor(protected readonly service: ClapService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Clap })
  async createClap(@common.Body() data: ClapCreateInput): Promise<Clap> {
    return await this.service.createClap({
      data: {
        ...data,

        setup: data.setup
          ? {
              connect: data.setup,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Clap] })
  @ApiNestedQuery(ClapFindManyArgs)
  async claps(@common.Req() request: Request): Promise<Clap[]> {
    const args = plainToClass(ClapFindManyArgs, request.query);
    return this.service.claps({
      ...args,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Clap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async clap(
    @common.Param() params: ClapWhereUniqueInput
  ): Promise<Clap | null> {
    const result = await this.service.clap({
      where: params,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Clap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClap(
    @common.Param() params: ClapWhereUniqueInput,
    @common.Body() data: ClapUpdateInput
  ): Promise<Clap | null> {
    try {
      return await this.service.updateClap({
        where: params,
        data: {
          ...data,

          setup: data.setup
            ? {
                connect: data.setup,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,

          setup: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Clap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClap(
    @common.Param() params: ClapWhereUniqueInput
  ): Promise<Clap | null> {
    try {
      return await this.service.deleteClap({
        where: params,
        select: {
          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,

          setup: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
