/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Clap as PrismaClap,
  Setup as PrismaSetup,
  User as PrismaUser,
} from "@prisma/client";

export class ClapServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ClapCountArgs, "select">): Promise<number> {
    return this.prisma.clap.count(args);
  }

  async claps(args: Prisma.ClapFindManyArgs): Promise<PrismaClap[]> {
    return this.prisma.clap.findMany(args);
  }
  async clap(args: Prisma.ClapFindUniqueArgs): Promise<PrismaClap | null> {
    return this.prisma.clap.findUnique(args);
  }
  async createClap(args: Prisma.ClapCreateArgs): Promise<PrismaClap> {
    return this.prisma.clap.create(args);
  }
  async updateClap(args: Prisma.ClapUpdateArgs): Promise<PrismaClap> {
    return this.prisma.clap.update(args);
  }
  async deleteClap(args: Prisma.ClapDeleteArgs): Promise<PrismaClap> {
    return this.prisma.clap.delete(args);
  }

  async getSetup(parentId: string): Promise<PrismaSetup | null> {
    return this.prisma.clap
      .findUnique({
        where: { id: parentId },
      })
      .setup();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.clap
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
