/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserSubscription } from "./UserSubscription";
import { UserSubscriptionCountArgs } from "./UserSubscriptionCountArgs";
import { UserSubscriptionFindManyArgs } from "./UserSubscriptionFindManyArgs";
import { UserSubscriptionFindUniqueArgs } from "./UserSubscriptionFindUniqueArgs";
import { CreateUserSubscriptionArgs } from "./CreateUserSubscriptionArgs";
import { UpdateUserSubscriptionArgs } from "./UpdateUserSubscriptionArgs";
import { DeleteUserSubscriptionArgs } from "./DeleteUserSubscriptionArgs";
import { SubscriptionPoolFindManyArgs } from "../../subscriptionPool/base/SubscriptionPoolFindManyArgs";
import { SubscriptionPool } from "../../subscriptionPool/base/SubscriptionPool";
import { TraderReferralEarningFindManyArgs } from "../../traderReferralEarning/base/TraderReferralEarningFindManyArgs";
import { TraderReferralEarning } from "../../traderReferralEarning/base/TraderReferralEarning";
import { Product } from "../../product/base/Product";
import { User } from "../../user/base/User";
import { UserSubscriptionService } from "../userSubscription.service";
@graphql.Resolver(() => UserSubscription)
export class UserSubscriptionResolverBase {
  constructor(protected readonly service: UserSubscriptionService) {}

  async _userSubscriptionsMeta(
    @graphql.Args() args: UserSubscriptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserSubscription])
  async userSubscriptions(
    @graphql.Args() args: UserSubscriptionFindManyArgs
  ): Promise<UserSubscription[]> {
    return this.service.userSubscriptions(args);
  }

  @graphql.Query(() => UserSubscription, { nullable: true })
  async userSubscription(
    @graphql.Args() args: UserSubscriptionFindUniqueArgs
  ): Promise<UserSubscription | null> {
    const result = await this.service.userSubscription(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserSubscription)
  async createUserSubscription(
    @graphql.Args() args: CreateUserSubscriptionArgs
  ): Promise<UserSubscription> {
    return await this.service.createUserSubscription({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,

        trader: args.data.trader
          ? {
              connect: args.data.trader,
            }
          : undefined,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => UserSubscription)
  async updateUserSubscription(
    @graphql.Args() args: UpdateUserSubscriptionArgs
  ): Promise<UserSubscription | null> {
    try {
      return await this.service.updateUserSubscription({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,

          trader: args.data.trader
            ? {
                connect: args.data.trader,
              }
            : undefined,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserSubscription)
  async deleteUserSubscription(
    @graphql.Args() args: DeleteUserSubscriptionArgs
  ): Promise<UserSubscription | null> {
    try {
      return await this.service.deleteUserSubscription(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [SubscriptionPool], { name: "subscriptionPool" })
  async findSubscriptionPool(
    @graphql.Parent() parent: UserSubscription,
    @graphql.Args() args: SubscriptionPoolFindManyArgs
  ): Promise<SubscriptionPool[]> {
    const results = await this.service.findSubscriptionPool(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TraderReferralEarning], {
    name: "traderReferralEarning",
  })
  async findTraderReferralEarning(
    @graphql.Parent() parent: UserSubscription,
    @graphql.Args() args: TraderReferralEarningFindManyArgs
  ): Promise<TraderReferralEarning[]> {
    const results = await this.service.findTraderReferralEarning(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: UserSubscription
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "trader",
  })
  async getTrader(
    @graphql.Parent() parent: UserSubscription
  ): Promise<User | null> {
    const result = await this.service.getTrader(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: UserSubscription
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
