/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsDate,
  IsOptional,
  IsBoolean,
  ValidateNested,
  IsString,
  MaxLength,
  IsInt,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { ClapCreateNestedManyWithoutUsersInput } from "./ClapCreateNestedManyWithoutUsersInput";
import { CopyTradeOrderCreateNestedManyWithoutUsersInput } from "./CopyTradeOrderCreateNestedManyWithoutUsersInput";
import { CopyTradeCreateNestedManyWithoutUsersInput } from "./CopyTradeCreateNestedManyWithoutUsersInput";
import { FollowNotifyCreateNestedManyWithoutUsersInput } from "./FollowNotifyCreateNestedManyWithoutUsersInput";
import { ReferralCodeCreateNestedManyWithoutUsersInput } from "./ReferralCodeCreateNestedManyWithoutUsersInput";
import { ReferralCodeWhereUniqueInput } from "../../referralCode/base/ReferralCodeWhereUniqueInput";
import { ReportCreateNestedManyWithoutUsersInput } from "./ReportCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SessionCreateNestedManyWithoutUsersInput } from "./SessionCreateNestedManyWithoutUsersInput";
import { SetupCreateNestedManyWithoutUsersInput } from "./SetupCreateNestedManyWithoutUsersInput";
import { TeamTraderCreateNestedManyWithoutUsersInput } from "./TeamTraderCreateNestedManyWithoutUsersInput";
import { TeamWhereUniqueInput } from "../../team/base/TeamWhereUniqueInput";
import { TraderProfileWhereUniqueInput } from "../../traderProfile/base/TraderProfileWhereUniqueInput";
import { TraderReferralEarningCreateNestedManyWithoutUsersInput } from "./TraderReferralEarningCreateNestedManyWithoutUsersInput";
import { TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput } from "./TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput";
import { TraderStatWhereUniqueInput } from "../../traderStat/base/TraderStatWhereUniqueInput";
import { TraderSuspensionWhereUniqueInput } from "../../traderSuspension/base/TraderSuspensionWhereUniqueInput";
import { UserNotificationCreateNestedManyWithoutUsersInput } from "./UserNotificationCreateNestedManyWithoutUsersInput";
import { UserSubscriptionCreateNestedManyWithoutUsersInput } from "./UserSubscriptionCreateNestedManyWithoutUsersInput";
import { WatchListCreateNestedManyWithoutUsersInput } from "./WatchListCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  approvedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  canCopyTrade!: boolean;

  @ApiProperty({
    required: false,
    type: () => ClapCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ClapCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ClapCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  clap?: ClapCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  copyTradeConnected!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  copyTradeMarket?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  copyTradeMarketUid?: string | null;

  @ApiProperty({
    required: false,
    type: () => CopyTradeOrderCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeOrderCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CopyTradeOrderCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  copyTradeOrder?: CopyTradeOrderCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CopyTradeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CopyTradeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  copyTradesCopyTradesTraderIdTouser?: CopyTradeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CopyTradeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CopyTradeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  copyTradesCopyTradesUserIdTouser?: CopyTradeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdById?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  deviceId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  emailValidationCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => FollowNotifyCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FollowNotifyCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FollowNotifyCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  followNotifyFollowNotifyTraderIdTouser?: FollowNotifyCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => FollowNotifyCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FollowNotifyCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FollowNotifyCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  followNotifyFollowNotifyUserIdTouser?: FollowNotifyCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  instagram?: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isAdmin!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isApproved!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isChangePassword!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isCopyNotify!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isCustomer!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isDeleted!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isEmailVerified!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isMembershipCompleted!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isNotify!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isTrader!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isTrending!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  language?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  monthlyR?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  monthlyRoi?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rate?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReferralCodeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReferralCodeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReferralCodeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  referralCodeReferralCodeTraderIdTouser?: ReferralCodeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ReferralCodeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ReferralCodeWhereUniqueInput)
  @IsOptional()
  @Field(() => ReferralCodeWhereUniqueInput, {
    nullable: true,
  })
  referralCodeUserReferralCodeIdToreferralCode?: ReferralCodeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  registrationToken?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  reportReportTraderIdTouser?: ReportCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  reportReportUserIdTouser?: ReportCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SessionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SessionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  sessions?: SessionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SetupCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SetupCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SetupCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  setup?: SetupCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  suspensionStartDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => TeamTraderCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TeamTraderCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TeamTraderCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  teamTraders?: TeamTraderCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TeamWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TeamWhereUniqueInput)
  @IsOptional()
  @Field(() => TeamWhereUniqueInput, {
    nullable: true,
  })
  teams?: TeamWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telegram?: string | null;

  @ApiProperty({
    required: false,
    type: () => TraderProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TraderProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => TraderProfileWhereUniqueInput, {
    nullable: true,
  })
  traderProfile?: TraderProfileWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TraderReferralEarningCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TraderReferralEarningCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TraderReferralEarningCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  traderReferralEarning?: TraderReferralEarningCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  traderSetupPnlPerformance?: TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TraderStatWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TraderStatWhereUniqueInput)
  @IsOptional()
  @Field(() => TraderStatWhereUniqueInput, {
    nullable: true,
  })
  traderStats?: TraderStatWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TraderSuspensionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TraderSuspensionWhereUniqueInput)
  @IsOptional()
  @Field(() => TraderSuspensionWhereUniqueInput, {
    nullable: true,
  })
  traderSuspension?: TraderSuspensionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  twitter?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  uid?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  updatedById?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserNotificationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserNotificationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserNotificationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userNotificationUserNotificationTraderIdTouser?: UserNotificationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserNotificationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserNotificationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserNotificationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userNotifications?: UserNotificationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserSubscriptionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserSubscriptionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserSubscriptionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userSubscriptionUserSubscriptionTraderIdTouser?: UserSubscriptionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserSubscriptionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserSubscriptionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserSubscriptionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userSubscriptions?: UserSubscriptionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;

  @ApiProperty({
    required: false,
    type: () => WatchListCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WatchListCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WatchListCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  watchList?: WatchListCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
