/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { ClapFindManyArgs } from "../../clap/base/ClapFindManyArgs";
import { Clap } from "../../clap/base/Clap";
import { ClapWhereUniqueInput } from "../../clap/base/ClapWhereUniqueInput";
import { CopyTradeOrderFindManyArgs } from "../../copyTradeOrder/base/CopyTradeOrderFindManyArgs";
import { CopyTradeOrder } from "../../copyTradeOrder/base/CopyTradeOrder";
import { CopyTradeOrderWhereUniqueInput } from "../../copyTradeOrder/base/CopyTradeOrderWhereUniqueInput";
import { CopyTradeFindManyArgs } from "../../copyTrade/base/CopyTradeFindManyArgs";
import { CopyTrade } from "../../copyTrade/base/CopyTrade";
import { CopyTradeWhereUniqueInput } from "../../copyTrade/base/CopyTradeWhereUniqueInput";
import { FollowNotifyFindManyArgs } from "../../followNotify/base/FollowNotifyFindManyArgs";
import { FollowNotify } from "../../followNotify/base/FollowNotify";
import { FollowNotifyWhereUniqueInput } from "../../followNotify/base/FollowNotifyWhereUniqueInput";
import { ReferralCodeFindManyArgs } from "../../referralCode/base/ReferralCodeFindManyArgs";
import { ReferralCode } from "../../referralCode/base/ReferralCode";
import { ReferralCodeWhereUniqueInput } from "../../referralCode/base/ReferralCodeWhereUniqueInput";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { ReportWhereUniqueInput } from "../../report/base/ReportWhereUniqueInput";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { SessionWhereUniqueInput } from "../../session/base/SessionWhereUniqueInput";
import { SetupFindManyArgs } from "../../setup/base/SetupFindManyArgs";
import { Setup } from "../../setup/base/Setup";
import { SetupWhereUniqueInput } from "../../setup/base/SetupWhereUniqueInput";
import { TeamTraderFindManyArgs } from "../../teamTrader/base/TeamTraderFindManyArgs";
import { TeamTrader } from "../../teamTrader/base/TeamTrader";
import { TeamTraderWhereUniqueInput } from "../../teamTrader/base/TeamTraderWhereUniqueInput";
import { TraderReferralEarningFindManyArgs } from "../../traderReferralEarning/base/TraderReferralEarningFindManyArgs";
import { TraderReferralEarning } from "../../traderReferralEarning/base/TraderReferralEarning";
import { TraderReferralEarningWhereUniqueInput } from "../../traderReferralEarning/base/TraderReferralEarningWhereUniqueInput";
import { TraderSetupPnlPerformanceFindManyArgs } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformanceFindManyArgs";
import { TraderSetupPnlPerformance } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformance";
import { TraderSetupPnlPerformanceWhereUniqueInput } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformanceWhereUniqueInput";
import { UserNotificationFindManyArgs } from "../../userNotification/base/UserNotificationFindManyArgs";
import { UserNotification } from "../../userNotification/base/UserNotification";
import { UserNotificationWhereUniqueInput } from "../../userNotification/base/UserNotificationWhereUniqueInput";
import { UserSubscriptionFindManyArgs } from "../../userSubscription/base/UserSubscriptionFindManyArgs";
import { UserSubscription } from "../../userSubscription/base/UserSubscription";
import { UserSubscriptionWhereUniqueInput } from "../../userSubscription/base/UserSubscriptionWhereUniqueInput";
import { WatchListFindManyArgs } from "../../watchList/base/WatchListFindManyArgs";
import { WatchList } from "../../watchList/base/WatchList";
import { WatchListWhereUniqueInput } from "../../watchList/base/WatchListWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        referralCodeUserReferralCodeIdToreferralCode:
          data.referralCodeUserReferralCodeIdToreferralCode
            ? {
                connect: data.referralCodeUserReferralCodeIdToreferralCode,
              }
            : undefined,

        teams: data.teams
          ? {
              connect: data.teams,
            }
          : undefined,

        traderProfile: data.traderProfile
          ? {
              connect: data.traderProfile,
            }
          : undefined,

        traderStats: data.traderStats
          ? {
              connect: data.traderStats,
            }
          : undefined,

        traderSuspension: data.traderSuspension
          ? {
              connect: data.traderSuspension,
            }
          : undefined,
      },
      select: {
        approvedAt: true,
        canCopyTrade: true,
        copyTradeConnected: true,
        copyTradeMarket: true,
        copyTradeMarketUid: true,
        createdAt: true,
        createdById: true,
        deviceId: true,
        email: true,
        emailValidationCode: true,
        firstName: true,
        id: true,
        image: true,
        instagram: true,
        isActive: true,
        isAdmin: true,
        isApproved: true,
        isChangePassword: true,
        isCopyNotify: true,
        isCustomer: true,
        isDeleted: true,
        isEmailVerified: true,
        isMembershipCompleted: true,
        isNotify: true,
        isTrader: true,
        isTrending: true,
        language: true,
        lastName: true,
        monthlyR: true,
        monthlyRoi: true,
        name: true,
        password: true,
        phone: true,
        rate: true,

        referralCodeUserReferralCodeIdToreferralCode: {
          select: {
            id: true,
          },
        },

        registrationToken: true,
        roles: true,
        suspensionStartDate: true,

        teams: {
          select: {
            id: true,
          },
        },

        telegram: true,

        traderProfile: {
          select: {
            id: true,
          },
        },

        traderStats: {
          select: {
            id: true,
          },
        },

        traderSuspension: {
          select: {
            id: true,
          },
        },

        twitter: true,
        uid: true,
        updatedAt: true,
        updatedById: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        approvedAt: true,
        canCopyTrade: true,
        copyTradeConnected: true,
        copyTradeMarket: true,
        copyTradeMarketUid: true,
        createdAt: true,
        createdById: true,
        deviceId: true,
        email: true,
        emailValidationCode: true,
        firstName: true,
        id: true,
        image: true,
        instagram: true,
        isActive: true,
        isAdmin: true,
        isApproved: true,
        isChangePassword: true,
        isCopyNotify: true,
        isCustomer: true,
        isDeleted: true,
        isEmailVerified: true,
        isMembershipCompleted: true,
        isNotify: true,
        isTrader: true,
        isTrending: true,
        language: true,
        lastName: true,
        monthlyR: true,
        monthlyRoi: true,
        name: true,
        password: true,
        phone: true,
        rate: true,

        referralCodeUserReferralCodeIdToreferralCode: {
          select: {
            id: true,
          },
        },

        registrationToken: true,
        roles: true,
        suspensionStartDate: true,

        teams: {
          select: {
            id: true,
          },
        },

        telegram: true,

        traderProfile: {
          select: {
            id: true,
          },
        },

        traderStats: {
          select: {
            id: true,
          },
        },

        traderSuspension: {
          select: {
            id: true,
          },
        },

        twitter: true,
        uid: true,
        updatedAt: true,
        updatedById: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        approvedAt: true,
        canCopyTrade: true,
        copyTradeConnected: true,
        copyTradeMarket: true,
        copyTradeMarketUid: true,
        createdAt: true,
        createdById: true,
        deviceId: true,
        email: true,
        emailValidationCode: true,
        firstName: true,
        id: true,
        image: true,
        instagram: true,
        isActive: true,
        isAdmin: true,
        isApproved: true,
        isChangePassword: true,
        isCopyNotify: true,
        isCustomer: true,
        isDeleted: true,
        isEmailVerified: true,
        isMembershipCompleted: true,
        isNotify: true,
        isTrader: true,
        isTrending: true,
        language: true,
        lastName: true,
        monthlyR: true,
        monthlyRoi: true,
        name: true,
        password: true,
        phone: true,
        rate: true,

        referralCodeUserReferralCodeIdToreferralCode: {
          select: {
            id: true,
          },
        },

        registrationToken: true,
        roles: true,
        suspensionStartDate: true,

        teams: {
          select: {
            id: true,
          },
        },

        telegram: true,

        traderProfile: {
          select: {
            id: true,
          },
        },

        traderStats: {
          select: {
            id: true,
          },
        },

        traderSuspension: {
          select: {
            id: true,
          },
        },

        twitter: true,
        uid: true,
        updatedAt: true,
        updatedById: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          referralCodeUserReferralCodeIdToreferralCode:
            data.referralCodeUserReferralCodeIdToreferralCode
              ? {
                  connect: data.referralCodeUserReferralCodeIdToreferralCode,
                }
              : undefined,

          teams: data.teams
            ? {
                connect: data.teams,
              }
            : undefined,

          traderProfile: data.traderProfile
            ? {
                connect: data.traderProfile,
              }
            : undefined,

          traderStats: data.traderStats
            ? {
                connect: data.traderStats,
              }
            : undefined,

          traderSuspension: data.traderSuspension
            ? {
                connect: data.traderSuspension,
              }
            : undefined,
        },
        select: {
          approvedAt: true,
          canCopyTrade: true,
          copyTradeConnected: true,
          copyTradeMarket: true,
          copyTradeMarketUid: true,
          createdAt: true,
          createdById: true,
          deviceId: true,
          email: true,
          emailValidationCode: true,
          firstName: true,
          id: true,
          image: true,
          instagram: true,
          isActive: true,
          isAdmin: true,
          isApproved: true,
          isChangePassword: true,
          isCopyNotify: true,
          isCustomer: true,
          isDeleted: true,
          isEmailVerified: true,
          isMembershipCompleted: true,
          isNotify: true,
          isTrader: true,
          isTrending: true,
          language: true,
          lastName: true,
          monthlyR: true,
          monthlyRoi: true,
          name: true,
          password: true,
          phone: true,
          rate: true,

          referralCodeUserReferralCodeIdToreferralCode: {
            select: {
              id: true,
            },
          },

          registrationToken: true,
          roles: true,
          suspensionStartDate: true,

          teams: {
            select: {
              id: true,
            },
          },

          telegram: true,

          traderProfile: {
            select: {
              id: true,
            },
          },

          traderStats: {
            select: {
              id: true,
            },
          },

          traderSuspension: {
            select: {
              id: true,
            },
          },

          twitter: true,
          uid: true,
          updatedAt: true,
          updatedById: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          approvedAt: true,
          canCopyTrade: true,
          copyTradeConnected: true,
          copyTradeMarket: true,
          copyTradeMarketUid: true,
          createdAt: true,
          createdById: true,
          deviceId: true,
          email: true,
          emailValidationCode: true,
          firstName: true,
          id: true,
          image: true,
          instagram: true,
          isActive: true,
          isAdmin: true,
          isApproved: true,
          isChangePassword: true,
          isCopyNotify: true,
          isCustomer: true,
          isDeleted: true,
          isEmailVerified: true,
          isMembershipCompleted: true,
          isNotify: true,
          isTrader: true,
          isTrending: true,
          language: true,
          lastName: true,
          monthlyR: true,
          monthlyRoi: true,
          name: true,
          password: true,
          phone: true,
          rate: true,

          referralCodeUserReferralCodeIdToreferralCode: {
            select: {
              id: true,
            },
          },

          registrationToken: true,
          roles: true,
          suspensionStartDate: true,

          teams: {
            select: {
              id: true,
            },
          },

          telegram: true,

          traderProfile: {
            select: {
              id: true,
            },
          },

          traderStats: {
            select: {
              id: true,
            },
          },

          traderSuspension: {
            select: {
              id: true,
            },
          },

          twitter: true,
          uid: true,
          updatedAt: true,
          updatedById: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/clap")
  @ApiNestedQuery(ClapFindManyArgs)
  async findClap(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Clap[]> {
    const query = plainToClass(ClapFindManyArgs, request.query);
    const results = await this.service.findClap(params.id, {
      ...query,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/clap")
  async connectClap(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ClapWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clap: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/clap")
  async updateClap(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ClapWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clap: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/clap")
  async disconnectClap(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ClapWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clap: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/copyTradeOrder")
  @ApiNestedQuery(CopyTradeOrderFindManyArgs)
  async findCopyTradeOrder(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<CopyTradeOrder[]> {
    const query = plainToClass(CopyTradeOrderFindManyArgs, request.query);
    const results = await this.service.findCopyTradeOrder(params.id, {
      ...query,
      select: {
        actPx: true,
        actSz: true,

        copyTrades: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        percentage: true,
        requestPx: true,
        requestSz: true,
        requestedAt: true,

        setup: {
          select: {
            id: true,
          },
        },

        side: true,
        status: true,
        statusAt: true,
        statusMessage: true,
        stopLossPx: true,
        takeProfitPx: true,
        tpValue: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/copyTradeOrder")
  async connectCopyTradeOrder(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradeOrder: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/copyTradeOrder")
  async updateCopyTradeOrder(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradeOrder: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/copyTradeOrder")
  async disconnectCopyTradeOrder(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradeOrder: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/copyTradesCopyTradesTraderIdTouser")
  @ApiNestedQuery(CopyTradeFindManyArgs)
  async findCopyTradesCopyTradesTraderIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<CopyTrade[]> {
    const query = plainToClass(CopyTradeFindManyArgs, request.query);
    const results = await this.service.findCopyTradesCopyTradesTraderIdTouser(
      params.id,
      {
        ...query,
        select: {
          activatedAt: true,
          assetSize: true,
          copiedAt: true,
          createdAt: true,
          createdById: true,
          errorMessage: true,
          errorNo: true,
          id: true,
          isDeleted: true,
          market: true,
          realizedPnl: true,
          realizedR: true,

          setup: {
            select: {
              id: true,
            },
          },

          state: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
          usdSize: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/copyTradesCopyTradesTraderIdTouser")
  async connectCopyTradesCopyTradesTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradesCopyTradesTraderIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/copyTradesCopyTradesTraderIdTouser")
  async updateCopyTradesCopyTradesTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradesCopyTradesTraderIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/copyTradesCopyTradesTraderIdTouser")
  async disconnectCopyTradesCopyTradesTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradesCopyTradesTraderIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/copyTradesCopyTradesUserIdTouser")
  @ApiNestedQuery(CopyTradeFindManyArgs)
  async findCopyTradesCopyTradesUserIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<CopyTrade[]> {
    const query = plainToClass(CopyTradeFindManyArgs, request.query);
    const results = await this.service.findCopyTradesCopyTradesUserIdTouser(
      params.id,
      {
        ...query,
        select: {
          activatedAt: true,
          assetSize: true,
          copiedAt: true,
          createdAt: true,
          createdById: true,
          errorMessage: true,
          errorNo: true,
          id: true,
          isDeleted: true,
          market: true,
          realizedPnl: true,
          realizedR: true,

          setup: {
            select: {
              id: true,
            },
          },

          state: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
          usdSize: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/copyTradesCopyTradesUserIdTouser")
  async connectCopyTradesCopyTradesUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradesCopyTradesUserIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/copyTradesCopyTradesUserIdTouser")
  async updateCopyTradesCopyTradesUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradesCopyTradesUserIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/copyTradesCopyTradesUserIdTouser")
  async disconnectCopyTradesCopyTradesUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradesCopyTradesUserIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/followNotifyFollowNotifyTraderIdTouser")
  @ApiNestedQuery(FollowNotifyFindManyArgs)
  async findFollowNotifyFollowNotifyTraderIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<FollowNotify[]> {
    const query = plainToClass(FollowNotifyFindManyArgs, request.query);
    const results =
      await this.service.findFollowNotifyFollowNotifyTraderIdTouser(params.id, {
        ...query,
        select: {
          block: true,
          createdAt: true,
          createdById: true,
          follow: true,
          id: true,
          isDeleted: true,
          notify: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/followNotifyFollowNotifyTraderIdTouser")
  async connectFollowNotifyFollowNotifyTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: FollowNotifyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      followNotifyFollowNotifyTraderIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/followNotifyFollowNotifyTraderIdTouser")
  async updateFollowNotifyFollowNotifyTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: FollowNotifyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      followNotifyFollowNotifyTraderIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/followNotifyFollowNotifyTraderIdTouser")
  async disconnectFollowNotifyFollowNotifyTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: FollowNotifyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      followNotifyFollowNotifyTraderIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/followNotifyFollowNotifyUserIdTouser")
  @ApiNestedQuery(FollowNotifyFindManyArgs)
  async findFollowNotifyFollowNotifyUserIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<FollowNotify[]> {
    const query = plainToClass(FollowNotifyFindManyArgs, request.query);
    const results = await this.service.findFollowNotifyFollowNotifyUserIdTouser(
      params.id,
      {
        ...query,
        select: {
          block: true,
          createdAt: true,
          createdById: true,
          follow: true,
          id: true,
          isDeleted: true,
          notify: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/followNotifyFollowNotifyUserIdTouser")
  async connectFollowNotifyFollowNotifyUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: FollowNotifyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      followNotifyFollowNotifyUserIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/followNotifyFollowNotifyUserIdTouser")
  async updateFollowNotifyFollowNotifyUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: FollowNotifyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      followNotifyFollowNotifyUserIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/followNotifyFollowNotifyUserIdTouser")
  async disconnectFollowNotifyFollowNotifyUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: FollowNotifyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      followNotifyFollowNotifyUserIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/referralCodeReferralCodeTraderIdTouser")
  @ApiNestedQuery(ReferralCodeFindManyArgs)
  async findReferralCodeReferralCodeTraderIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<ReferralCode[]> {
    const query = plainToClass(ReferralCodeFindManyArgs, request.query);
    const results =
      await this.service.findReferralCodeReferralCodeTraderIdTouser(params.id, {
        ...query,
        select: {
          code: true,
          createdAt: true,
          createdById: true,
          id: true,
          isActive: true,
          isDeleted: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
        },
      });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/referralCodeReferralCodeTraderIdTouser")
  async connectReferralCodeReferralCodeTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReferralCodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      referralCodeReferralCodeTraderIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/referralCodeReferralCodeTraderIdTouser")
  async updateReferralCodeReferralCodeTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReferralCodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      referralCodeReferralCodeTraderIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/referralCodeReferralCodeTraderIdTouser")
  async disconnectReferralCodeReferralCodeTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReferralCodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      referralCodeReferralCodeTraderIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/reportReportTraderIdTouser")
  @ApiNestedQuery(ReportFindManyArgs)
  async findReportReportTraderIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Report[]> {
    const query = plainToClass(ReportFindManyArgs, request.query);
    const results = await this.service.findReportReportTraderIdTouser(
      params.id,
      {
        ...query,
        select: {
          content: true,
          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,

          setup: {
            select: {
              id: true,
            },
          },

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reportReportTraderIdTouser")
  async connectReportReportTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reportReportTraderIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reportReportTraderIdTouser")
  async updateReportReportTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reportReportTraderIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reportReportTraderIdTouser")
  async disconnectReportReportTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reportReportTraderIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/reportReportUserIdTouser")
  @ApiNestedQuery(ReportFindManyArgs)
  async findReportReportUserIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Report[]> {
    const query = plainToClass(ReportFindManyArgs, request.query);
    const results = await this.service.findReportReportUserIdTouser(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reportReportUserIdTouser")
  async connectReportReportUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reportReportUserIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reportReportUserIdTouser")
  async updateReportReportUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reportReportUserIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reportReportUserIdTouser")
  async disconnectReportReportUserIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reportReportUserIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/sessions")
  @ApiNestedQuery(SessionFindManyArgs)
  async findSessions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Session[]> {
    const query = plainToClass(SessionFindManyArgs, request.query);
    const results = await this.service.findSessions(params.id, {
      ...query,
      select: {
        createdAt: true,
        deletedAt: true,
        hash: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sessions")
  async connectSessions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sessions")
  async updateSessions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sessions")
  async disconnectSessions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/setup")
  @ApiNestedQuery(SetupFindManyArgs)
  async findSetup(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Setup[]> {
    const query = plainToClass(SetupFindManyArgs, request.query);
    const results = await this.service.findSetup(params.id, {
      ...query,
      select: {
        activatedStopValue: true,
        activationDate: true,
        category: true,
        clapCount: true,
        closeDate: true,
        closePrice: true,
        closedById: true,
        coinName: true,
        createdAt: true,
        createdById: true,
        duration: true,
        entryValue: true,
        entryValueEnd: true,
        id: true,
        image: true,
        imageSuccess: true,
        initialEntryValue: true,
        initialEntryValueEnd: true,
        initialProfitTaking1: true,
        initialProfitTaking2: true,
        initialProfitTaking3: true,
        initialProfitTakingAmount1: true,
        initialProfitTakingAmount2: true,
        initialProfitTakingAmount3: true,
        initialRr: true,
        initialStopValue: true,
        isActive: true,
        isDeleted: true,
        isHidden: true,
        isStop: true,
        isTargeted: true,
        isTp1: true,
        isTp2: true,
        isTp3: true,
        position: true,
        previousEntryValue: true,
        previousEntryValueEnd: true,
        previousProfitTaking1: true,
        previousProfitTaking2: true,
        previousProfitTaking3: true,
        previousProfitTakingAmount1: true,
        previousProfitTakingAmount2: true,
        previousProfitTakingAmount3: true,
        previousStopValue: true,
        profitTaking1: true,
        profitTaking2: true,
        profitTaking3: true,
        profitTakingAmount1: true,
        profitTakingAmount2: true,
        profitTakingAmount3: true,
        rValue: true,
        status: true,
        stopDate: true,
        stopDistance: true,
        stopValue: true,
        subStatus: true,
        tags: true,
        targetDate: true,
        tp1Date: true,
        tp2Date: true,
        tp3Date: true,

        trader: {
          select: {
            id: true,
          },
        },

        traderSetupPnlPerformance: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/setup")
  async connectSetup(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SetupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      setup: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/setup")
  async updateSetup(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SetupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      setup: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/setup")
  async disconnectSetup(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SetupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      setup: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/teamTraders")
  @ApiNestedQuery(TeamTraderFindManyArgs)
  async findTeamTraders(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TeamTrader[]> {
    const query = plainToClass(TeamTraderFindManyArgs, request.query);
    const results = await this.service.findTeamTraders(params.id, {
      ...query,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        teams: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teamTraders")
  async connectTeamTraders(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeamTraderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamTraders: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teamTraders")
  async updateTeamTraders(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeamTraderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamTraders: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teamTraders")
  async disconnectTeamTraders(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeamTraderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamTraders: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/traderReferralEarning")
  @ApiNestedQuery(TraderReferralEarningFindManyArgs)
  async findTraderReferralEarning(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TraderReferralEarning[]> {
    const query = plainToClass(
      TraderReferralEarningFindManyArgs,
      request.query
    );
    const results = await this.service.findTraderReferralEarning(params.id, {
      ...query,
      select: {
        amount: true,
        cancellationDate: true,
        createdAt: true,
        createdById: true,
        id: true,
        installment: true,
        installments: true,
        isCancelled: true,
        isDeleted: true,
        isPaid: true,
        isWithdrawal: true,
        paidDate: true,
        traderEarnDate: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },

        userSubscription: {
          select: {
            id: true,
          },
        },

        withdrawalDate: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/traderReferralEarning")
  async connectTraderReferralEarning(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TraderReferralEarningWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      traderReferralEarning: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/traderReferralEarning")
  async updateTraderReferralEarning(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TraderReferralEarningWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      traderReferralEarning: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/traderReferralEarning")
  async disconnectTraderReferralEarning(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TraderReferralEarningWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      traderReferralEarning: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/traderSetupPnlPerformance")
  @ApiNestedQuery(TraderSetupPnlPerformanceFindManyArgs)
  async findTraderSetupPnlPerformance(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TraderSetupPnlPerformance[]> {
    const query = plainToClass(
      TraderSetupPnlPerformanceFindManyArgs,
      request.query
    );
    const results = await this.service.findTraderSetupPnlPerformance(
      params.id,
      {
        ...query,
        select: {
          createdAt: true,
          estimatedPnl: true,
          estimatedPnlRate: true,
          feeRate: true,
          id: true,
          pnl: true,
          pnlRate: true,
          rR: true,

          setup: {
            select: {
              id: true,
            },
          },

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/traderSetupPnlPerformance")
  async connectTraderSetupPnlPerformance(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TraderSetupPnlPerformanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      traderSetupPnlPerformance: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/traderSetupPnlPerformance")
  async updateTraderSetupPnlPerformance(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TraderSetupPnlPerformanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      traderSetupPnlPerformance: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/traderSetupPnlPerformance")
  async disconnectTraderSetupPnlPerformance(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TraderSetupPnlPerformanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      traderSetupPnlPerformance: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userNotificationUserNotificationTraderIdTouser")
  @ApiNestedQuery(UserNotificationFindManyArgs)
  async findUserNotificationUserNotificationTraderIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserNotification[]> {
    const query = plainToClass(UserNotificationFindManyArgs, request.query);
    const results =
      await this.service.findUserNotificationUserNotificationTraderIdTouser(
        params.id,
        {
          ...query,
          select: {
            columnValue: true,
            createdAt: true,
            createdById: true,
            id: true,
            isDeleted: true,
            isRead: true,
            message: true,
            messageId: true,

            setup: {
              select: {
                id: true,
              },
            },

            trader: {
              select: {
                id: true,
              },
            },

            typeField: true,
            updatedAt: true,
            updatedById: true,
            updatedColumn: true,

            user: {
              select: {
                id: true,
              },
            },
          },
        }
      );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userNotificationUserNotificationTraderIdTouser")
  async connectUserNotificationUserNotificationTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotificationUserNotificationTraderIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userNotificationUserNotificationTraderIdTouser")
  async updateUserNotificationUserNotificationTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotificationUserNotificationTraderIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userNotificationUserNotificationTraderIdTouser")
  async disconnectUserNotificationUserNotificationTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotificationUserNotificationTraderIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userNotifications")
  @ApiNestedQuery(UserNotificationFindManyArgs)
  async findUserNotifications(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserNotification[]> {
    const query = plainToClass(UserNotificationFindManyArgs, request.query);
    const results = await this.service.findUserNotifications(params.id, {
      ...query,
      select: {
        columnValue: true,
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        isRead: true,
        message: true,
        messageId: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
        updatedById: true,
        updatedColumn: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userNotifications")
  async connectUserNotifications(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotifications: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userNotifications")
  async updateUserNotifications(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotifications: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userNotifications")
  async disconnectUserNotifications(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotifications: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userSubscriptionUserSubscriptionTraderIdTouser")
  @ApiNestedQuery(UserSubscriptionFindManyArgs)
  async findUserSubscriptionUserSubscriptionTraderIdTouser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserSubscription[]> {
    const query = plainToClass(UserSubscriptionFindManyArgs, request.query);
    const results =
      await this.service.findUserSubscriptionUserSubscriptionTraderIdTouser(
        params.id,
        {
          ...query,
          select: {
            autoRenewProductCode: true,
            autoRenewStatus: true,
            createdAt: true,
            createdById: true,
            currency: true,
            data: true,
            expireDate: true,
            id: true,
            isCancelled: true,
            isDeleted: true,
            isExpired: true,
            isPaymentReceived: true,
            isTrial: true,
            market: true,
            price: true,

            product: {
              select: {
                id: true,
              },
            },

            rawData: true,
            startDate: true,

            trader: {
              select: {
                id: true,
              },
            },

            transactionId: true,
            updatedAt: true,
            updatedById: true,

            user: {
              select: {
                id: true,
              },
            },
          },
        }
      );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userSubscriptionUserSubscriptionTraderIdTouser")
  async connectUserSubscriptionUserSubscriptionTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserSubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userSubscriptionUserSubscriptionTraderIdTouser: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userSubscriptionUserSubscriptionTraderIdTouser")
  async updateUserSubscriptionUserSubscriptionTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserSubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userSubscriptionUserSubscriptionTraderIdTouser: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userSubscriptionUserSubscriptionTraderIdTouser")
  async disconnectUserSubscriptionUserSubscriptionTraderIdTouser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserSubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userSubscriptionUserSubscriptionTraderIdTouser: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userSubscriptions")
  @ApiNestedQuery(UserSubscriptionFindManyArgs)
  async findUserSubscriptions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserSubscription[]> {
    const query = plainToClass(UserSubscriptionFindManyArgs, request.query);
    const results = await this.service.findUserSubscriptions(params.id, {
      ...query,
      select: {
        autoRenewProductCode: true,
        autoRenewStatus: true,
        createdAt: true,
        createdById: true,
        currency: true,
        data: true,
        expireDate: true,
        id: true,
        isCancelled: true,
        isDeleted: true,
        isExpired: true,
        isPaymentReceived: true,
        isTrial: true,
        market: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        rawData: true,
        startDate: true,

        trader: {
          select: {
            id: true,
          },
        },

        transactionId: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userSubscriptions")
  async connectUserSubscriptions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserSubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userSubscriptions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userSubscriptions")
  async updateUserSubscriptions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserSubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userSubscriptions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userSubscriptions")
  async disconnectUserSubscriptions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserSubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userSubscriptions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/watchList")
  @ApiNestedQuery(WatchListFindManyArgs)
  async findWatchList(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<WatchList[]> {
    const query = plainToClass(WatchListFindManyArgs, request.query);
    const results = await this.service.findWatchList(params.id, {
      ...query,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/watchList")
  async connectWatchList(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WatchListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      watchList: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/watchList")
  async updateWatchList(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WatchListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      watchList: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/watchList")
  async disconnectWatchList(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WatchListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      watchList: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
