/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { User } from "./User";
import { UserCountArgs } from "./UserCountArgs";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserFindUniqueArgs } from "./UserFindUniqueArgs";
import { CreateUserArgs } from "./CreateUserArgs";
import { UpdateUserArgs } from "./UpdateUserArgs";
import { DeleteUserArgs } from "./DeleteUserArgs";
import { ClapFindManyArgs } from "../../clap/base/ClapFindManyArgs";
import { Clap } from "../../clap/base/Clap";
import { CopyTradeOrderFindManyArgs } from "../../copyTradeOrder/base/CopyTradeOrderFindManyArgs";
import { CopyTradeOrder } from "../../copyTradeOrder/base/CopyTradeOrder";
import { CopyTradeFindManyArgs } from "../../copyTrade/base/CopyTradeFindManyArgs";
import { CopyTrade } from "../../copyTrade/base/CopyTrade";
import { FollowNotifyFindManyArgs } from "../../followNotify/base/FollowNotifyFindManyArgs";
import { FollowNotify } from "../../followNotify/base/FollowNotify";
import { ReferralCodeFindManyArgs } from "../../referralCode/base/ReferralCodeFindManyArgs";
import { ReferralCode } from "../../referralCode/base/ReferralCode";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { SetupFindManyArgs } from "../../setup/base/SetupFindManyArgs";
import { Setup } from "../../setup/base/Setup";
import { TeamTraderFindManyArgs } from "../../teamTrader/base/TeamTraderFindManyArgs";
import { TeamTrader } from "../../teamTrader/base/TeamTrader";
import { TraderReferralEarningFindManyArgs } from "../../traderReferralEarning/base/TraderReferralEarningFindManyArgs";
import { TraderReferralEarning } from "../../traderReferralEarning/base/TraderReferralEarning";
import { TraderSetupPnlPerformanceFindManyArgs } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformanceFindManyArgs";
import { TraderSetupPnlPerformance } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformance";
import { UserNotificationFindManyArgs } from "../../userNotification/base/UserNotificationFindManyArgs";
import { UserNotification } from "../../userNotification/base/UserNotification";
import { UserSubscriptionFindManyArgs } from "../../userSubscription/base/UserSubscriptionFindManyArgs";
import { UserSubscription } from "../../userSubscription/base/UserSubscription";
import { WatchListFindManyArgs } from "../../watchList/base/WatchListFindManyArgs";
import { WatchList } from "../../watchList/base/WatchList";
import { Team } from "../../team/base/Team";
import { TraderProfile } from "../../traderProfile/base/TraderProfile";
import { TraderStat } from "../../traderStat/base/TraderStat";
import { TraderSuspension } from "../../traderSuspension/base/TraderSuspension";
import { UserService } from "../user.service";
@graphql.Resolver(() => User)
export class UserResolverBase {
  constructor(protected readonly service: UserService) {}

  async _usersMeta(
    @graphql.Args() args: UserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [User])
  async users(@graphql.Args() args: UserFindManyArgs): Promise<User[]> {
    return this.service.users(args);
  }

  @graphql.Query(() => User, { nullable: true })
  async user(@graphql.Args() args: UserFindUniqueArgs): Promise<User | null> {
    const result = await this.service.user(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => User)
  async createUser(@graphql.Args() args: CreateUserArgs): Promise<User> {
    return await this.service.createUser({
      ...args,
      data: {
        ...args.data,

        referralCodeUserReferralCodeIdToreferralCode: args.data
          .referralCodeUserReferralCodeIdToreferralCode
          ? {
              connect: args.data.referralCodeUserReferralCodeIdToreferralCode,
            }
          : undefined,

        teams: args.data.teams
          ? {
              connect: args.data.teams,
            }
          : undefined,

        traderProfile: args.data.traderProfile
          ? {
              connect: args.data.traderProfile,
            }
          : undefined,

        traderStats: args.data.traderStats
          ? {
              connect: args.data.traderStats,
            }
          : undefined,

        traderSuspension: args.data.traderSuspension
          ? {
              connect: args.data.traderSuspension,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => User)
  async updateUser(@graphql.Args() args: UpdateUserArgs): Promise<User | null> {
    try {
      return await this.service.updateUser({
        ...args,
        data: {
          ...args.data,

          referralCodeUserReferralCodeIdToreferralCode: args.data
            .referralCodeUserReferralCodeIdToreferralCode
            ? {
                connect: args.data.referralCodeUserReferralCodeIdToreferralCode,
              }
            : undefined,

          teams: args.data.teams
            ? {
                connect: args.data.teams,
              }
            : undefined,

          traderProfile: args.data.traderProfile
            ? {
                connect: args.data.traderProfile,
              }
            : undefined,

          traderStats: args.data.traderStats
            ? {
                connect: args.data.traderStats,
              }
            : undefined,

          traderSuspension: args.data.traderSuspension
            ? {
                connect: args.data.traderSuspension,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => User)
  async deleteUser(@graphql.Args() args: DeleteUserArgs): Promise<User | null> {
    try {
      return await this.service.deleteUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Clap], { name: "clap" })
  async findClap(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ClapFindManyArgs
  ): Promise<Clap[]> {
    const results = await this.service.findClap(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [CopyTradeOrder], { name: "copyTradeOrder" })
  async findCopyTradeOrder(
    @graphql.Parent() parent: User,
    @graphql.Args() args: CopyTradeOrderFindManyArgs
  ): Promise<CopyTradeOrder[]> {
    const results = await this.service.findCopyTradeOrder(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [CopyTrade], {
    name: "copyTradesCopyTradesTraderIdTouser",
  })
  async findCopyTradesCopyTradesTraderIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: CopyTradeFindManyArgs
  ): Promise<CopyTrade[]> {
    const results = await this.service.findCopyTradesCopyTradesTraderIdTouser(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [CopyTrade], {
    name: "copyTradesCopyTradesUserIdTouser",
  })
  async findCopyTradesCopyTradesUserIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: CopyTradeFindManyArgs
  ): Promise<CopyTrade[]> {
    const results = await this.service.findCopyTradesCopyTradesUserIdTouser(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [FollowNotify], {
    name: "followNotifyFollowNotifyTraderIdTouser",
  })
  async findFollowNotifyFollowNotifyTraderIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: FollowNotifyFindManyArgs
  ): Promise<FollowNotify[]> {
    const results =
      await this.service.findFollowNotifyFollowNotifyTraderIdTouser(
        parent.id,
        args
      );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [FollowNotify], {
    name: "followNotifyFollowNotifyUserIdTouser",
  })
  async findFollowNotifyFollowNotifyUserIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: FollowNotifyFindManyArgs
  ): Promise<FollowNotify[]> {
    const results = await this.service.findFollowNotifyFollowNotifyUserIdTouser(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ReferralCode], {
    name: "referralCodeReferralCodeTraderIdTouser",
  })
  async findReferralCodeReferralCodeTraderIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ReferralCodeFindManyArgs
  ): Promise<ReferralCode[]> {
    const results =
      await this.service.findReferralCodeReferralCodeTraderIdTouser(
        parent.id,
        args
      );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Report], { name: "reportReportTraderIdTouser" })
  async findReportReportTraderIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ReportFindManyArgs
  ): Promise<Report[]> {
    const results = await this.service.findReportReportTraderIdTouser(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Report], { name: "reportReportUserIdTouser" })
  async findReportReportUserIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ReportFindManyArgs
  ): Promise<Report[]> {
    const results = await this.service.findReportReportUserIdTouser(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Session], { name: "sessions" })
  async findSessions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: SessionFindManyArgs
  ): Promise<Session[]> {
    const results = await this.service.findSessions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Setup], { name: "setup" })
  async findSetup(
    @graphql.Parent() parent: User,
    @graphql.Args() args: SetupFindManyArgs
  ): Promise<Setup[]> {
    const results = await this.service.findSetup(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TeamTrader], { name: "teamTraders" })
  async findTeamTraders(
    @graphql.Parent() parent: User,
    @graphql.Args() args: TeamTraderFindManyArgs
  ): Promise<TeamTrader[]> {
    const results = await this.service.findTeamTraders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TraderReferralEarning], {
    name: "traderReferralEarning",
  })
  async findTraderReferralEarning(
    @graphql.Parent() parent: User,
    @graphql.Args() args: TraderReferralEarningFindManyArgs
  ): Promise<TraderReferralEarning[]> {
    const results = await this.service.findTraderReferralEarning(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TraderSetupPnlPerformance], {
    name: "traderSetupPnlPerformance",
  })
  async findTraderSetupPnlPerformance(
    @graphql.Parent() parent: User,
    @graphql.Args() args: TraderSetupPnlPerformanceFindManyArgs
  ): Promise<TraderSetupPnlPerformance[]> {
    const results = await this.service.findTraderSetupPnlPerformance(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [UserNotification], {
    name: "userNotificationUserNotificationTraderIdTouser",
  })
  async findUserNotificationUserNotificationTraderIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: UserNotificationFindManyArgs
  ): Promise<UserNotification[]> {
    const results =
      await this.service.findUserNotificationUserNotificationTraderIdTouser(
        parent.id,
        args
      );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [UserNotification], { name: "userNotifications" })
  async findUserNotifications(
    @graphql.Parent() parent: User,
    @graphql.Args() args: UserNotificationFindManyArgs
  ): Promise<UserNotification[]> {
    const results = await this.service.findUserNotifications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [UserSubscription], {
    name: "userSubscriptionUserSubscriptionTraderIdTouser",
  })
  async findUserSubscriptionUserSubscriptionTraderIdTouser(
    @graphql.Parent() parent: User,
    @graphql.Args() args: UserSubscriptionFindManyArgs
  ): Promise<UserSubscription[]> {
    const results =
      await this.service.findUserSubscriptionUserSubscriptionTraderIdTouser(
        parent.id,
        args
      );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [UserSubscription], { name: "userSubscriptions" })
  async findUserSubscriptions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: UserSubscriptionFindManyArgs
  ): Promise<UserSubscription[]> {
    const results = await this.service.findUserSubscriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [WatchList], { name: "watchList" })
  async findWatchList(
    @graphql.Parent() parent: User,
    @graphql.Args() args: WatchListFindManyArgs
  ): Promise<WatchList[]> {
    const results = await this.service.findWatchList(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => ReferralCode, {
    nullable: true,
    name: "referralCodeUserReferralCodeIdToreferralCode",
  })
  async getReferralCodeUserReferralCodeIdToreferralCode(
    @graphql.Parent() parent: User
  ): Promise<ReferralCode | null> {
    const result =
      await this.service.getReferralCodeUserReferralCodeIdToreferralCode(
        parent.id
      );

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Team, {
    nullable: true,
    name: "teams",
  })
  async getTeams(@graphql.Parent() parent: User): Promise<Team | null> {
    const result = await this.service.getTeams(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => TraderProfile, {
    nullable: true,
    name: "traderProfile",
  })
  async getTraderProfile(
    @graphql.Parent() parent: User
  ): Promise<TraderProfile | null> {
    const result = await this.service.getTraderProfile(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => TraderStat, {
    nullable: true,
    name: "traderStats",
  })
  async getTraderStats(
    @graphql.Parent() parent: User
  ): Promise<TraderStat | null> {
    const result = await this.service.getTraderStats(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => TraderSuspension, {
    nullable: true,
    name: "traderSuspension",
  })
  async getTraderSuspension(
    @graphql.Parent() parent: User
  ): Promise<TraderSuspension | null> {
    const result = await this.service.getTraderSuspension(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
