/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TraderSuspensionService } from "../traderSuspension.service";
import { TraderSuspensionCreateInput } from "./TraderSuspensionCreateInput";
import { TraderSuspension } from "./TraderSuspension";
import { TraderSuspensionFindManyArgs } from "./TraderSuspensionFindManyArgs";
import { TraderSuspensionWhereUniqueInput } from "./TraderSuspensionWhereUniqueInput";
import { TraderSuspensionUpdateInput } from "./TraderSuspensionUpdateInput";

export class TraderSuspensionControllerBase {
  constructor(protected readonly service: TraderSuspensionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TraderSuspension })
  async createTraderSuspension(
    @common.Body() data: TraderSuspensionCreateInput
  ): Promise<TraderSuspension> {
    return await this.service.createTraderSuspension({
      data: {
        ...data,

        trader: {
          connect: data.trader,
        },
      },
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        suspensionEndDate: true,
        suspensionStartDate: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TraderSuspension] })
  @ApiNestedQuery(TraderSuspensionFindManyArgs)
  async traderSuspensions(
    @common.Req() request: Request
  ): Promise<TraderSuspension[]> {
    const args = plainToClass(TraderSuspensionFindManyArgs, request.query);
    return this.service.traderSuspensions({
      ...args,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        suspensionEndDate: true,
        suspensionStartDate: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TraderSuspension })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async traderSuspension(
    @common.Param() params: TraderSuspensionWhereUniqueInput
  ): Promise<TraderSuspension | null> {
    const result = await this.service.traderSuspension({
      where: params,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        suspensionEndDate: true,
        suspensionStartDate: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TraderSuspension })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTraderSuspension(
    @common.Param() params: TraderSuspensionWhereUniqueInput,
    @common.Body() data: TraderSuspensionUpdateInput
  ): Promise<TraderSuspension | null> {
    try {
      return await this.service.updateTraderSuspension({
        where: params,
        data: {
          ...data,

          trader: {
            connect: data.trader,
          },
        },
        select: {
          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,
          suspensionEndDate: true,
          suspensionStartDate: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TraderSuspension })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTraderSuspension(
    @common.Param() params: TraderSuspensionWhereUniqueInput
  ): Promise<TraderSuspension | null> {
    try {
      return await this.service.deleteTraderSuspension({
        where: params,
        select: {
          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,
          suspensionEndDate: true,
          suspensionStartDate: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
