/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TraderSuspension } from "./TraderSuspension";
import { TraderSuspensionCountArgs } from "./TraderSuspensionCountArgs";
import { TraderSuspensionFindManyArgs } from "./TraderSuspensionFindManyArgs";
import { TraderSuspensionFindUniqueArgs } from "./TraderSuspensionFindUniqueArgs";
import { CreateTraderSuspensionArgs } from "./CreateTraderSuspensionArgs";
import { UpdateTraderSuspensionArgs } from "./UpdateTraderSuspensionArgs";
import { DeleteTraderSuspensionArgs } from "./DeleteTraderSuspensionArgs";
import { User } from "../../user/base/User";
import { TraderSuspensionService } from "../traderSuspension.service";
@graphql.Resolver(() => TraderSuspension)
export class TraderSuspensionResolverBase {
  constructor(protected readonly service: TraderSuspensionService) {}

  async _traderSuspensionsMeta(
    @graphql.Args() args: TraderSuspensionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TraderSuspension])
  async traderSuspensions(
    @graphql.Args() args: TraderSuspensionFindManyArgs
  ): Promise<TraderSuspension[]> {
    return this.service.traderSuspensions(args);
  }

  @graphql.Query(() => TraderSuspension, { nullable: true })
  async traderSuspension(
    @graphql.Args() args: TraderSuspensionFindUniqueArgs
  ): Promise<TraderSuspension | null> {
    const result = await this.service.traderSuspension(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TraderSuspension)
  async createTraderSuspension(
    @graphql.Args() args: CreateTraderSuspensionArgs
  ): Promise<TraderSuspension> {
    return await this.service.createTraderSuspension({
      ...args,
      data: {
        ...args.data,

        trader: {
          connect: args.data.trader,
        },
      },
    });
  }

  @graphql.Mutation(() => TraderSuspension)
  async updateTraderSuspension(
    @graphql.Args() args: UpdateTraderSuspensionArgs
  ): Promise<TraderSuspension | null> {
    try {
      return await this.service.updateTraderSuspension({
        ...args,
        data: {
          ...args.data,

          trader: {
            connect: args.data.trader,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TraderSuspension)
  async deleteTraderSuspension(
    @graphql.Args() args: DeleteTraderSuspensionArgs
  ): Promise<TraderSuspension | null> {
    try {
      return await this.service.deleteTraderSuspension(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "trader",
  })
  async getTrader(
    @graphql.Parent() parent: TraderSuspension
  ): Promise<User | null> {
    const result = await this.service.getTrader(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
