/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SetupValueHistory } from "./SetupValueHistory";
import { SetupValueHistoryCountArgs } from "./SetupValueHistoryCountArgs";
import { SetupValueHistoryFindManyArgs } from "./SetupValueHistoryFindManyArgs";
import { SetupValueHistoryFindUniqueArgs } from "./SetupValueHistoryFindUniqueArgs";
import { CreateSetupValueHistoryArgs } from "./CreateSetupValueHistoryArgs";
import { UpdateSetupValueHistoryArgs } from "./UpdateSetupValueHistoryArgs";
import { DeleteSetupValueHistoryArgs } from "./DeleteSetupValueHistoryArgs";
import { Setup } from "../../setup/base/Setup";
import { SetupValueHistoryService } from "../setupValueHistory.service";
@graphql.Resolver(() => SetupValueHistory)
export class SetupValueHistoryResolverBase {
  constructor(protected readonly service: SetupValueHistoryService) {}

  async _setupValueHistoriesMeta(
    @graphql.Args() args: SetupValueHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SetupValueHistory])
  async setupValueHistories(
    @graphql.Args() args: SetupValueHistoryFindManyArgs
  ): Promise<SetupValueHistory[]> {
    return this.service.setupValueHistories(args);
  }

  @graphql.Query(() => SetupValueHistory, { nullable: true })
  async setupValueHistory(
    @graphql.Args() args: SetupValueHistoryFindUniqueArgs
  ): Promise<SetupValueHistory | null> {
    const result = await this.service.setupValueHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SetupValueHistory)
  async createSetupValueHistory(
    @graphql.Args() args: CreateSetupValueHistoryArgs
  ): Promise<SetupValueHistory> {
    return await this.service.createSetupValueHistory({
      ...args,
      data: {
        ...args.data,

        setup: args.data.setup
          ? {
              connect: args.data.setup,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SetupValueHistory)
  async updateSetupValueHistory(
    @graphql.Args() args: UpdateSetupValueHistoryArgs
  ): Promise<SetupValueHistory | null> {
    try {
      return await this.service.updateSetupValueHistory({
        ...args,
        data: {
          ...args.data,

          setup: args.data.setup
            ? {
                connect: args.data.setup,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SetupValueHistory)
  async deleteSetupValueHistory(
    @graphql.Args() args: DeleteSetupValueHistoryArgs
  ): Promise<SetupValueHistory | null> {
    try {
      return await this.service.deleteSetupValueHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Setup, {
    nullable: true,
    name: "setup",
  })
  async getSetup(
    @graphql.Parent() parent: SetupValueHistory
  ): Promise<Setup | null> {
    const result = await this.service.getSetup(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
