/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SetupValueHistoryService } from "../setupValueHistory.service";
import { SetupValueHistoryCreateInput } from "./SetupValueHistoryCreateInput";
import { SetupValueHistory } from "./SetupValueHistory";
import { SetupValueHistoryFindManyArgs } from "./SetupValueHistoryFindManyArgs";
import { SetupValueHistoryWhereUniqueInput } from "./SetupValueHistoryWhereUniqueInput";
import { SetupValueHistoryUpdateInput } from "./SetupValueHistoryUpdateInput";

export class SetupValueHistoryControllerBase {
  constructor(protected readonly service: SetupValueHistoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SetupValueHistory })
  async createSetupValueHistory(
    @common.Body() data: SetupValueHistoryCreateInput
  ): Promise<SetupValueHistory> {
    return await this.service.createSetupValueHistory({
      data: {
        ...data,

        setup: data.setup
          ? {
              connect: data.setup,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fieldField: true,
        id: true,

        setup: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SetupValueHistory] })
  @ApiNestedQuery(SetupValueHistoryFindManyArgs)
  async setupValueHistories(
    @common.Req() request: Request
  ): Promise<SetupValueHistory[]> {
    const args = plainToClass(SetupValueHistoryFindManyArgs, request.query);
    return this.service.setupValueHistories({
      ...args,
      select: {
        createdAt: true,
        fieldField: true,
        id: true,

        setup: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SetupValueHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async setupValueHistory(
    @common.Param() params: SetupValueHistoryWhereUniqueInput
  ): Promise<SetupValueHistory | null> {
    const result = await this.service.setupValueHistory({
      where: params,
      select: {
        createdAt: true,
        fieldField: true,
        id: true,

        setup: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SetupValueHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSetupValueHistory(
    @common.Param() params: SetupValueHistoryWhereUniqueInput,
    @common.Body() data: SetupValueHistoryUpdateInput
  ): Promise<SetupValueHistory | null> {
    try {
      return await this.service.updateSetupValueHistory({
        where: params,
        data: {
          ...data,

          setup: data.setup
            ? {
                connect: data.setup,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fieldField: true,
          id: true,

          setup: {
            select: {
              id: true,
            },
          },

          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SetupValueHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSetupValueHistory(
    @common.Param() params: SetupValueHistoryWhereUniqueInput
  ): Promise<SetupValueHistory | null> {
    try {
      return await this.service.deleteSetupValueHistory({
        where: params,
        select: {
          createdAt: true,
          fieldField: true,
          id: true,

          setup: {
            select: {
              id: true,
            },
          },

          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
