/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SetupValueHistory as PrismaSetupValueHistory,
  Setup as PrismaSetup,
} from "@prisma/client";

export class SetupValueHistoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SetupValueHistoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.setupValueHistory.count(args);
  }

  async setupValueHistories(
    args: Prisma.SetupValueHistoryFindManyArgs
  ): Promise<PrismaSetupValueHistory[]> {
    return this.prisma.setupValueHistory.findMany(args);
  }
  async setupValueHistory(
    args: Prisma.SetupValueHistoryFindUniqueArgs
  ): Promise<PrismaSetupValueHistory | null> {
    return this.prisma.setupValueHistory.findUnique(args);
  }
  async createSetupValueHistory(
    args: Prisma.SetupValueHistoryCreateArgs
  ): Promise<PrismaSetupValueHistory> {
    return this.prisma.setupValueHistory.create(args);
  }
  async updateSetupValueHistory(
    args: Prisma.SetupValueHistoryUpdateArgs
  ): Promise<PrismaSetupValueHistory> {
    return this.prisma.setupValueHistory.update(args);
  }
  async deleteSetupValueHistory(
    args: Prisma.SetupValueHistoryDeleteArgs
  ): Promise<PrismaSetupValueHistory> {
    return this.prisma.setupValueHistory.delete(args);
  }

  async getSetup(parentId: string): Promise<PrismaSetup | null> {
    return this.prisma.setupValueHistory
      .findUnique({
        where: { id: parentId },
      })
      .setup();
  }
}
