/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AppStoreProductPrice } from "./AppStoreProductPrice";
import { AppStoreProductPriceCountArgs } from "./AppStoreProductPriceCountArgs";
import { AppStoreProductPriceFindManyArgs } from "./AppStoreProductPriceFindManyArgs";
import { AppStoreProductPriceFindUniqueArgs } from "./AppStoreProductPriceFindUniqueArgs";
import { CreateAppStoreProductPriceArgs } from "./CreateAppStoreProductPriceArgs";
import { UpdateAppStoreProductPriceArgs } from "./UpdateAppStoreProductPriceArgs";
import { DeleteAppStoreProductPriceArgs } from "./DeleteAppStoreProductPriceArgs";
import { AppStoreProductPriceService } from "../appStoreProductPrice.service";
@graphql.Resolver(() => AppStoreProductPrice)
export class AppStoreProductPriceResolverBase {
  constructor(protected readonly service: AppStoreProductPriceService) {}

  async _appStoreProductPricesMeta(
    @graphql.Args() args: AppStoreProductPriceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AppStoreProductPrice])
  async appStoreProductPrices(
    @graphql.Args() args: AppStoreProductPriceFindManyArgs
  ): Promise<AppStoreProductPrice[]> {
    return this.service.appStoreProductPrices(args);
  }

  @graphql.Query(() => AppStoreProductPrice, { nullable: true })
  async appStoreProductPrice(
    @graphql.Args() args: AppStoreProductPriceFindUniqueArgs
  ): Promise<AppStoreProductPrice | null> {
    const result = await this.service.appStoreProductPrice(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AppStoreProductPrice)
  async createAppStoreProductPrice(
    @graphql.Args() args: CreateAppStoreProductPriceArgs
  ): Promise<AppStoreProductPrice> {
    return await this.service.createAppStoreProductPrice({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AppStoreProductPrice)
  async updateAppStoreProductPrice(
    @graphql.Args() args: UpdateAppStoreProductPriceArgs
  ): Promise<AppStoreProductPrice | null> {
    try {
      return await this.service.updateAppStoreProductPrice({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AppStoreProductPrice)
  async deleteAppStoreProductPrice(
    @graphql.Args() args: DeleteAppStoreProductPriceArgs
  ): Promise<AppStoreProductPrice | null> {
    try {
      return await this.service.deleteAppStoreProductPrice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
