/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CalendarTextService } from "../calendarText.service";
import { CalendarTextCreateInput } from "./CalendarTextCreateInput";
import { CalendarText } from "./CalendarText";
import { CalendarTextFindManyArgs } from "./CalendarTextFindManyArgs";
import { CalendarTextWhereUniqueInput } from "./CalendarTextWhereUniqueInput";
import { CalendarTextUpdateInput } from "./CalendarTextUpdateInput";

export class CalendarTextControllerBase {
  constructor(protected readonly service: CalendarTextService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CalendarText })
  async createCalendarText(
    @common.Body() data: CalendarTextCreateInput
  ): Promise<CalendarText> {
    return await this.service.createCalendarText({
      data: {
        ...data,

        calendar: {
          connect: data.calendar,
        },
      },
      select: {
        acroExpand: true,
        alsoCalled: true,

        calendar: {
          select: {
            id: true,
          },
        },

        ccNotes: true,
        ccNotice: true,
        country: true,
        derivedVia: true,
        description: true,
        frequency: true,
        id: true,
        language: true,
        measures: true,
        source: true,
        speaker: true,
        title: true,
        usualEffect: true,
        whyTraderscare: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CalendarText] })
  @ApiNestedQuery(CalendarTextFindManyArgs)
  async calendarTexts(@common.Req() request: Request): Promise<CalendarText[]> {
    const args = plainToClass(CalendarTextFindManyArgs, request.query);
    return this.service.calendarTexts({
      ...args,
      select: {
        acroExpand: true,
        alsoCalled: true,

        calendar: {
          select: {
            id: true,
          },
        },

        ccNotes: true,
        ccNotice: true,
        country: true,
        derivedVia: true,
        description: true,
        frequency: true,
        id: true,
        language: true,
        measures: true,
        source: true,
        speaker: true,
        title: true,
        usualEffect: true,
        whyTraderscare: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CalendarText })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async calendarText(
    @common.Param() params: CalendarTextWhereUniqueInput
  ): Promise<CalendarText | null> {
    const result = await this.service.calendarText({
      where: params,
      select: {
        acroExpand: true,
        alsoCalled: true,

        calendar: {
          select: {
            id: true,
          },
        },

        ccNotes: true,
        ccNotice: true,
        country: true,
        derivedVia: true,
        description: true,
        frequency: true,
        id: true,
        language: true,
        measures: true,
        source: true,
        speaker: true,
        title: true,
        usualEffect: true,
        whyTraderscare: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CalendarText })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCalendarText(
    @common.Param() params: CalendarTextWhereUniqueInput,
    @common.Body() data: CalendarTextUpdateInput
  ): Promise<CalendarText | null> {
    try {
      return await this.service.updateCalendarText({
        where: params,
        data: {
          ...data,

          calendar: {
            connect: data.calendar,
          },
        },
        select: {
          acroExpand: true,
          alsoCalled: true,

          calendar: {
            select: {
              id: true,
            },
          },

          ccNotes: true,
          ccNotice: true,
          country: true,
          derivedVia: true,
          description: true,
          frequency: true,
          id: true,
          language: true,
          measures: true,
          source: true,
          speaker: true,
          title: true,
          usualEffect: true,
          whyTraderscare: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CalendarText })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCalendarText(
    @common.Param() params: CalendarTextWhereUniqueInput
  ): Promise<CalendarText | null> {
    try {
      return await this.service.deleteCalendarText({
        where: params,
        select: {
          acroExpand: true,
          alsoCalled: true,

          calendar: {
            select: {
              id: true,
            },
          },

          ccNotes: true,
          ccNotice: true,
          country: true,
          derivedVia: true,
          description: true,
          frequency: true,
          id: true,
          language: true,
          measures: true,
          source: true,
          speaker: true,
          title: true,
          usualEffect: true,
          whyTraderscare: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
