/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TraderSetupPnlPerformanceService } from "../traderSetupPnlPerformance.service";
import { TraderSetupPnlPerformanceCreateInput } from "./TraderSetupPnlPerformanceCreateInput";
import { TraderSetupPnlPerformance } from "./TraderSetupPnlPerformance";
import { TraderSetupPnlPerformanceFindManyArgs } from "./TraderSetupPnlPerformanceFindManyArgs";
import { TraderSetupPnlPerformanceWhereUniqueInput } from "./TraderSetupPnlPerformanceWhereUniqueInput";
import { TraderSetupPnlPerformanceUpdateInput } from "./TraderSetupPnlPerformanceUpdateInput";

export class TraderSetupPnlPerformanceControllerBase {
  constructor(protected readonly service: TraderSetupPnlPerformanceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TraderSetupPnlPerformance })
  async createTraderSetupPnlPerformance(
    @common.Body() data: TraderSetupPnlPerformanceCreateInput
  ): Promise<TraderSetupPnlPerformance> {
    return await this.service.createTraderSetupPnlPerformance({
      data: {
        ...data,

        setup: {
          connect: data.setup,
        },

        trader: data.trader
          ? {
              connect: data.trader,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        estimatedPnl: true,
        estimatedPnlRate: true,
        feeRate: true,
        id: true,
        pnl: true,
        pnlRate: true,
        rR: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TraderSetupPnlPerformance] })
  @ApiNestedQuery(TraderSetupPnlPerformanceFindManyArgs)
  async traderSetupPnlPerformances(
    @common.Req() request: Request
  ): Promise<TraderSetupPnlPerformance[]> {
    const args = plainToClass(
      TraderSetupPnlPerformanceFindManyArgs,
      request.query
    );
    return this.service.traderSetupPnlPerformances({
      ...args,
      select: {
        createdAt: true,
        estimatedPnl: true,
        estimatedPnlRate: true,
        feeRate: true,
        id: true,
        pnl: true,
        pnlRate: true,
        rR: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TraderSetupPnlPerformance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async traderSetupPnlPerformance(
    @common.Param() params: TraderSetupPnlPerformanceWhereUniqueInput
  ): Promise<TraderSetupPnlPerformance | null> {
    const result = await this.service.traderSetupPnlPerformance({
      where: params,
      select: {
        createdAt: true,
        estimatedPnl: true,
        estimatedPnlRate: true,
        feeRate: true,
        id: true,
        pnl: true,
        pnlRate: true,
        rR: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TraderSetupPnlPerformance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTraderSetupPnlPerformance(
    @common.Param() params: TraderSetupPnlPerformanceWhereUniqueInput,
    @common.Body() data: TraderSetupPnlPerformanceUpdateInput
  ): Promise<TraderSetupPnlPerformance | null> {
    try {
      return await this.service.updateTraderSetupPnlPerformance({
        where: params,
        data: {
          ...data,

          setup: {
            connect: data.setup,
          },

          trader: data.trader
            ? {
                connect: data.trader,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          estimatedPnl: true,
          estimatedPnlRate: true,
          feeRate: true,
          id: true,
          pnl: true,
          pnlRate: true,
          rR: true,

          setup: {
            select: {
              id: true,
            },
          },

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TraderSetupPnlPerformance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTraderSetupPnlPerformance(
    @common.Param() params: TraderSetupPnlPerformanceWhereUniqueInput
  ): Promise<TraderSetupPnlPerformance | null> {
    try {
      return await this.service.deleteTraderSetupPnlPerformance({
        where: params,
        select: {
          createdAt: true,
          estimatedPnl: true,
          estimatedPnlRate: true,
          feeRate: true,
          id: true,
          pnl: true,
          pnlRate: true,
          rR: true,

          setup: {
            select: {
              id: true,
            },
          },

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
