/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  TraderSetupPnlPerformance as PrismaTraderSetupPnlPerformance,
  Setup as PrismaSetup,
  User as PrismaUser,
} from "@prisma/client";

export class TraderSetupPnlPerformanceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TraderSetupPnlPerformanceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.traderSetupPnlPerformance.count(args);
  }

  async traderSetupPnlPerformances(
    args: Prisma.TraderSetupPnlPerformanceFindManyArgs
  ): Promise<PrismaTraderSetupPnlPerformance[]> {
    return this.prisma.traderSetupPnlPerformance.findMany(args);
  }
  async traderSetupPnlPerformance(
    args: Prisma.TraderSetupPnlPerformanceFindUniqueArgs
  ): Promise<PrismaTraderSetupPnlPerformance | null> {
    return this.prisma.traderSetupPnlPerformance.findUnique(args);
  }
  async createTraderSetupPnlPerformance(
    args: Prisma.TraderSetupPnlPerformanceCreateArgs
  ): Promise<PrismaTraderSetupPnlPerformance> {
    return this.prisma.traderSetupPnlPerformance.create(args);
  }
  async updateTraderSetupPnlPerformance(
    args: Prisma.TraderSetupPnlPerformanceUpdateArgs
  ): Promise<PrismaTraderSetupPnlPerformance> {
    return this.prisma.traderSetupPnlPerformance.update(args);
  }
  async deleteTraderSetupPnlPerformance(
    args: Prisma.TraderSetupPnlPerformanceDeleteArgs
  ): Promise<PrismaTraderSetupPnlPerformance> {
    return this.prisma.traderSetupPnlPerformance.delete(args);
  }

  async getSetup(parentId: string): Promise<PrismaSetup | null> {
    return this.prisma.traderSetupPnlPerformance
      .findUnique({
        where: { id: parentId },
      })
      .setup();
  }

  async getTrader(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.traderSetupPnlPerformance
      .findUnique({
        where: { id: parentId },
      })
      .trader();
  }
}
