/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FollowNotify } from "./FollowNotify";
import { FollowNotifyCountArgs } from "./FollowNotifyCountArgs";
import { FollowNotifyFindManyArgs } from "./FollowNotifyFindManyArgs";
import { FollowNotifyFindUniqueArgs } from "./FollowNotifyFindUniqueArgs";
import { CreateFollowNotifyArgs } from "./CreateFollowNotifyArgs";
import { UpdateFollowNotifyArgs } from "./UpdateFollowNotifyArgs";
import { DeleteFollowNotifyArgs } from "./DeleteFollowNotifyArgs";
import { User } from "../../user/base/User";
import { FollowNotifyService } from "../followNotify.service";
@graphql.Resolver(() => FollowNotify)
export class FollowNotifyResolverBase {
  constructor(protected readonly service: FollowNotifyService) {}

  async _followNotifiesMeta(
    @graphql.Args() args: FollowNotifyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FollowNotify])
  async followNotifies(
    @graphql.Args() args: FollowNotifyFindManyArgs
  ): Promise<FollowNotify[]> {
    return this.service.followNotifies(args);
  }

  @graphql.Query(() => FollowNotify, { nullable: true })
  async followNotify(
    @graphql.Args() args: FollowNotifyFindUniqueArgs
  ): Promise<FollowNotify | null> {
    const result = await this.service.followNotify(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FollowNotify)
  async createFollowNotify(
    @graphql.Args() args: CreateFollowNotifyArgs
  ): Promise<FollowNotify> {
    return await this.service.createFollowNotify({
      ...args,
      data: {
        ...args.data,

        trader: args.data.trader
          ? {
              connect: args.data.trader,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FollowNotify)
  async updateFollowNotify(
    @graphql.Args() args: UpdateFollowNotifyArgs
  ): Promise<FollowNotify | null> {
    try {
      return await this.service.updateFollowNotify({
        ...args,
        data: {
          ...args.data,

          trader: args.data.trader
            ? {
                connect: args.data.trader,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FollowNotify)
  async deleteFollowNotify(
    @graphql.Args() args: DeleteFollowNotifyArgs
  ): Promise<FollowNotify | null> {
    try {
      return await this.service.deleteFollowNotify(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "trader",
  })
  async getTrader(
    @graphql.Parent() parent: FollowNotify
  ): Promise<User | null> {
    const result = await this.service.getTrader(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: FollowNotify): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
