/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CopyTradeOrderService } from "../copyTradeOrder.service";
import { CopyTradeOrderCreateInput } from "./CopyTradeOrderCreateInput";
import { CopyTradeOrder } from "./CopyTradeOrder";
import { CopyTradeOrderFindManyArgs } from "./CopyTradeOrderFindManyArgs";
import { CopyTradeOrderWhereUniqueInput } from "./CopyTradeOrderWhereUniqueInput";
import { CopyTradeOrderUpdateInput } from "./CopyTradeOrderUpdateInput";

export class CopyTradeOrderControllerBase {
  constructor(protected readonly service: CopyTradeOrderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CopyTradeOrder })
  async createCopyTradeOrder(
    @common.Body() data: CopyTradeOrderCreateInput
  ): Promise<CopyTradeOrder> {
    return await this.service.createCopyTradeOrder({
      data: {
        ...data,

        copyTrades: data.copyTrades
          ? {
              connect: data.copyTrades,
            }
          : undefined,

        setup: data.setup
          ? {
              connect: data.setup,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        actPx: true,
        actSz: true,

        copyTrades: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        percentage: true,
        requestPx: true,
        requestSz: true,
        requestedAt: true,

        setup: {
          select: {
            id: true,
          },
        },

        side: true,
        status: true,
        statusAt: true,
        statusMessage: true,
        stopLossPx: true,
        takeProfitPx: true,
        tpValue: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CopyTradeOrder] })
  @ApiNestedQuery(CopyTradeOrderFindManyArgs)
  async copyTradeOrders(
    @common.Req() request: Request
  ): Promise<CopyTradeOrder[]> {
    const args = plainToClass(CopyTradeOrderFindManyArgs, request.query);
    return this.service.copyTradeOrders({
      ...args,
      select: {
        actPx: true,
        actSz: true,

        copyTrades: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        percentage: true,
        requestPx: true,
        requestSz: true,
        requestedAt: true,

        setup: {
          select: {
            id: true,
          },
        },

        side: true,
        status: true,
        statusAt: true,
        statusMessage: true,
        stopLossPx: true,
        takeProfitPx: true,
        tpValue: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CopyTradeOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async copyTradeOrder(
    @common.Param() params: CopyTradeOrderWhereUniqueInput
  ): Promise<CopyTradeOrder | null> {
    const result = await this.service.copyTradeOrder({
      where: params,
      select: {
        actPx: true,
        actSz: true,

        copyTrades: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        percentage: true,
        requestPx: true,
        requestSz: true,
        requestedAt: true,

        setup: {
          select: {
            id: true,
          },
        },

        side: true,
        status: true,
        statusAt: true,
        statusMessage: true,
        stopLossPx: true,
        takeProfitPx: true,
        tpValue: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CopyTradeOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCopyTradeOrder(
    @common.Param() params: CopyTradeOrderWhereUniqueInput,
    @common.Body() data: CopyTradeOrderUpdateInput
  ): Promise<CopyTradeOrder | null> {
    try {
      return await this.service.updateCopyTradeOrder({
        where: params,
        data: {
          ...data,

          copyTrades: data.copyTrades
            ? {
                connect: data.copyTrades,
              }
            : undefined,

          setup: data.setup
            ? {
                connect: data.setup,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          actPx: true,
          actSz: true,

          copyTrades: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,
          percentage: true,
          requestPx: true,
          requestSz: true,
          requestedAt: true,

          setup: {
            select: {
              id: true,
            },
          },

          side: true,
          status: true,
          statusAt: true,
          statusMessage: true,
          stopLossPx: true,
          takeProfitPx: true,
          tpValue: true,
          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CopyTradeOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCopyTradeOrder(
    @common.Param() params: CopyTradeOrderWhereUniqueInput
  ): Promise<CopyTradeOrder | null> {
    try {
      return await this.service.deleteCopyTradeOrder({
        where: params,
        select: {
          actPx: true,
          actSz: true,

          copyTrades: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          createdById: true,
          id: true,
          isDeleted: true,
          percentage: true,
          requestPx: true,
          requestSz: true,
          requestedAt: true,

          setup: {
            select: {
              id: true,
            },
          },

          side: true,
          status: true,
          statusAt: true,
          statusMessage: true,
          stopLossPx: true,
          takeProfitPx: true,
          tpValue: true,
          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
