/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  TraderStat as PrismaTraderStat,
  User as PrismaUser,
} from "@prisma/client";

export class TraderStatServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TraderStatCountArgs, "select">
  ): Promise<number> {
    return this.prisma.traderStat.count(args);
  }

  async traderStats(
    args: Prisma.TraderStatFindManyArgs
  ): Promise<PrismaTraderStat[]> {
    return this.prisma.traderStat.findMany(args);
  }
  async traderStat(
    args: Prisma.TraderStatFindUniqueArgs
  ): Promise<PrismaTraderStat | null> {
    return this.prisma.traderStat.findUnique(args);
  }
  async createTraderStat(
    args: Prisma.TraderStatCreateArgs
  ): Promise<PrismaTraderStat> {
    return this.prisma.traderStat.create(args);
  }
  async updateTraderStat(
    args: Prisma.TraderStatUpdateArgs
  ): Promise<PrismaTraderStat> {
    return this.prisma.traderStat.update(args);
  }
  async deleteTraderStat(
    args: Prisma.TraderStatDeleteArgs
  ): Promise<PrismaTraderStat> {
    return this.prisma.traderStat.delete(args);
  }

  async getTrader(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.traderStat
      .findUnique({
        where: { id: parentId },
      })
      .trader();
  }
}
