/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TraderReferralEarning } from "./TraderReferralEarning";
import { TraderReferralEarningCountArgs } from "./TraderReferralEarningCountArgs";
import { TraderReferralEarningFindManyArgs } from "./TraderReferralEarningFindManyArgs";
import { TraderReferralEarningFindUniqueArgs } from "./TraderReferralEarningFindUniqueArgs";
import { CreateTraderReferralEarningArgs } from "./CreateTraderReferralEarningArgs";
import { UpdateTraderReferralEarningArgs } from "./UpdateTraderReferralEarningArgs";
import { DeleteTraderReferralEarningArgs } from "./DeleteTraderReferralEarningArgs";
import { User } from "../../user/base/User";
import { UserSubscription } from "../../userSubscription/base/UserSubscription";
import { TraderReferralEarningService } from "../traderReferralEarning.service";
@graphql.Resolver(() => TraderReferralEarning)
export class TraderReferralEarningResolverBase {
  constructor(protected readonly service: TraderReferralEarningService) {}

  async _traderReferralEarningsMeta(
    @graphql.Args() args: TraderReferralEarningCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TraderReferralEarning])
  async traderReferralEarnings(
    @graphql.Args() args: TraderReferralEarningFindManyArgs
  ): Promise<TraderReferralEarning[]> {
    return this.service.traderReferralEarnings(args);
  }

  @graphql.Query(() => TraderReferralEarning, { nullable: true })
  async traderReferralEarning(
    @graphql.Args() args: TraderReferralEarningFindUniqueArgs
  ): Promise<TraderReferralEarning | null> {
    const result = await this.service.traderReferralEarning(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TraderReferralEarning)
  async createTraderReferralEarning(
    @graphql.Args() args: CreateTraderReferralEarningArgs
  ): Promise<TraderReferralEarning> {
    return await this.service.createTraderReferralEarning({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,

        userSubscription: args.data.userSubscription
          ? {
              connect: args.data.userSubscription,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TraderReferralEarning)
  async updateTraderReferralEarning(
    @graphql.Args() args: UpdateTraderReferralEarningArgs
  ): Promise<TraderReferralEarning | null> {
    try {
      return await this.service.updateTraderReferralEarning({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,

          userSubscription: args.data.userSubscription
            ? {
                connect: args.data.userSubscription,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TraderReferralEarning)
  async deleteTraderReferralEarning(
    @graphql.Args() args: DeleteTraderReferralEarningArgs
  ): Promise<TraderReferralEarning | null> {
    try {
      return await this.service.deleteTraderReferralEarning(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: TraderReferralEarning
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => UserSubscription, {
    nullable: true,
    name: "userSubscription",
  })
  async getUserSubscription(
    @graphql.Parent() parent: TraderReferralEarning
  ): Promise<UserSubscription | null> {
    const result = await this.service.getUserSubscription(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
