/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TraderReferralEarningService } from "../traderReferralEarning.service";
import { TraderReferralEarningCreateInput } from "./TraderReferralEarningCreateInput";
import { TraderReferralEarning } from "./TraderReferralEarning";
import { TraderReferralEarningFindManyArgs } from "./TraderReferralEarningFindManyArgs";
import { TraderReferralEarningWhereUniqueInput } from "./TraderReferralEarningWhereUniqueInput";
import { TraderReferralEarningUpdateInput } from "./TraderReferralEarningUpdateInput";

export class TraderReferralEarningControllerBase {
  constructor(protected readonly service: TraderReferralEarningService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TraderReferralEarning })
  async createTraderReferralEarning(
    @common.Body() data: TraderReferralEarningCreateInput
  ): Promise<TraderReferralEarning> {
    return await this.service.createTraderReferralEarning({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        userSubscription: data.userSubscription
          ? {
              connect: data.userSubscription,
            }
          : undefined,
      },
      select: {
        amount: true,
        cancellationDate: true,
        createdAt: true,
        createdById: true,
        id: true,
        installment: true,
        installments: true,
        isCancelled: true,
        isDeleted: true,
        isPaid: true,
        isWithdrawal: true,
        paidDate: true,
        traderEarnDate: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },

        userSubscription: {
          select: {
            id: true,
          },
        },

        withdrawalDate: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TraderReferralEarning] })
  @ApiNestedQuery(TraderReferralEarningFindManyArgs)
  async traderReferralEarnings(
    @common.Req() request: Request
  ): Promise<TraderReferralEarning[]> {
    const args = plainToClass(TraderReferralEarningFindManyArgs, request.query);
    return this.service.traderReferralEarnings({
      ...args,
      select: {
        amount: true,
        cancellationDate: true,
        createdAt: true,
        createdById: true,
        id: true,
        installment: true,
        installments: true,
        isCancelled: true,
        isDeleted: true,
        isPaid: true,
        isWithdrawal: true,
        paidDate: true,
        traderEarnDate: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },

        userSubscription: {
          select: {
            id: true,
          },
        },

        withdrawalDate: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TraderReferralEarning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async traderReferralEarning(
    @common.Param() params: TraderReferralEarningWhereUniqueInput
  ): Promise<TraderReferralEarning | null> {
    const result = await this.service.traderReferralEarning({
      where: params,
      select: {
        amount: true,
        cancellationDate: true,
        createdAt: true,
        createdById: true,
        id: true,
        installment: true,
        installments: true,
        isCancelled: true,
        isDeleted: true,
        isPaid: true,
        isWithdrawal: true,
        paidDate: true,
        traderEarnDate: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },

        userSubscription: {
          select: {
            id: true,
          },
        },

        withdrawalDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TraderReferralEarning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTraderReferralEarning(
    @common.Param() params: TraderReferralEarningWhereUniqueInput,
    @common.Body() data: TraderReferralEarningUpdateInput
  ): Promise<TraderReferralEarning | null> {
    try {
      return await this.service.updateTraderReferralEarning({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          userSubscription: data.userSubscription
            ? {
                connect: data.userSubscription,
              }
            : undefined,
        },
        select: {
          amount: true,
          cancellationDate: true,
          createdAt: true,
          createdById: true,
          id: true,
          installment: true,
          installments: true,
          isCancelled: true,
          isDeleted: true,
          isPaid: true,
          isWithdrawal: true,
          paidDate: true,
          traderEarnDate: true,
          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },

          userSubscription: {
            select: {
              id: true,
            },
          },

          withdrawalDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TraderReferralEarning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTraderReferralEarning(
    @common.Param() params: TraderReferralEarningWhereUniqueInput
  ): Promise<TraderReferralEarning | null> {
    try {
      return await this.service.deleteTraderReferralEarning({
        where: params,
        select: {
          amount: true,
          cancellationDate: true,
          createdAt: true,
          createdById: true,
          id: true,
          installment: true,
          installments: true,
          isCancelled: true,
          isDeleted: true,
          isPaid: true,
          isWithdrawal: true,
          paidDate: true,
          traderEarnDate: true,
          updatedAt: true,
          updatedById: true,

          user: {
            select: {
              id: true,
            },
          },

          userSubscription: {
            select: {
              id: true,
            },
          },

          withdrawalDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
