import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { ProductWhereUniqueInput } from "../product/ProductWhereUniqueInput";
import { SubscriptionPoolListRelationFilter } from "../subscriptionPool/SubscriptionPoolListRelationFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { TraderReferralEarningListRelationFilter } from "../traderReferralEarning/TraderReferralEarningListRelationFilter";

export type UserSubscriptionWhereInput = {
  autoRenewProductCode?: StringNullableFilter;
  autoRenewStatus?: BooleanFilter;
  createdAt?: DateTimeNullableFilter;
  createdById?: StringNullableFilter;
  currency?: StringNullableFilter;
  data?: StringFilter;
  expireDate?: DateTimeFilter;
  id?: StringFilter;
  isCancelled?: BooleanFilter;
  isDeleted?: BooleanFilter;
  isExpired?: BooleanFilter;
  isPaymentReceived?: BooleanNullableFilter;
  isTrial?: BooleanFilter;
  market?: StringFilter;
  price?: FloatNullableFilter;
  product?: ProductWhereUniqueInput;
  rawData?: StringFilter;
  startDate?: DateTimeFilter;
  subscriptionPool?: SubscriptionPoolListRelationFilter;
  trader?: UserWhereUniqueInput;
  traderReferralEarning?: TraderReferralEarningListRelationFilter;
  transactionId?: StringFilter;
  updatedAt?: DateTimeNullableFilter;
  updatedById?: StringNullableFilter;
  user?: UserWhereUniqueInput;
};
