/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Max,
  IsOptional,
  IsDate,
  IsEnum,
  ValidateNested,
  IsInt,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";

import { Type } from "class-transformer";
import { EnumSetupCategory } from "./EnumSetupCategory";
import { ClapCreateNestedManyWithoutSetupsInput } from "./ClapCreateNestedManyWithoutSetupsInput";
import { CopyTradeOrderCreateNestedManyWithoutSetupsInput } from "./CopyTradeOrderCreateNestedManyWithoutSetupsInput";
import { CopyTradeCreateNestedManyWithoutSetupsInput } from "./CopyTradeCreateNestedManyWithoutSetupsInput";
import { EnumSetupDuration } from "./EnumSetupDuration";
import { EnumSetupPosition } from "./EnumSetupPosition";
import { ReportCreateNestedManyWithoutSetupsInput } from "./ReportCreateNestedManyWithoutSetupsInput";
import { SetupValueHistoryCreateNestedManyWithoutSetupsInput } from "./SetupValueHistoryCreateNestedManyWithoutSetupsInput";
import { EnumSetupStatus } from "./EnumSetupStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { TraderSetupPnlPerformanceWhereUniqueInput } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformanceWhereUniqueInput";
import { UserNotificationCreateNestedManyWithoutSetupsInput } from "./UserNotificationCreateNestedManyWithoutSetupsInput";
import { WatchListCreateNestedManyWithoutSetupsInput } from "./WatchListCreateNestedManyWithoutSetupsInput";

@InputType()
class SetupCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  activatedStopValue?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  activationDate?: Date | null;

  @ApiProperty({
    required: true,
    enum: EnumSetupCategory,
  })
  @IsEnum(EnumSetupCategory)
  @Field(() => EnumSetupCategory)
  category!: "spot" | "futures";

  @ApiProperty({
    required: false,
    type: () => ClapCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => ClapCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => ClapCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  clap?: ClapCreateNestedManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  clapCount?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  closeDate?: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  closePrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  closedById?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  coinName!: string;

  @ApiProperty({
    required: false,
    type: () => CopyTradeOrderCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeOrderCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => CopyTradeOrderCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  copyTradeOrder?: CopyTradeOrderCreateNestedManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: () => CopyTradeCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => CopyTradeCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  copyTrades?: CopyTradeCreateNestedManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdById?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSetupDuration,
  })
  @IsEnum(EnumSetupDuration)
  @IsOptional()
  @Field(() => EnumSetupDuration, {
    nullable: true,
  })
  duration?: "shortterm" | "midterm" | "longterm" | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  entryValue!: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  entryValueEnd?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageSuccess?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialEntryValue?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialEntryValueEnd?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTaking1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTaking2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTaking3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTakingAmount1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTakingAmount2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTakingAmount3?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  initialRr?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialStopValue?: number | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isDeleted!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isHidden!: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isStop?: boolean | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isTargeted!: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTp1?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTp2?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTp3?: boolean | null;

  @ApiProperty({
    required: false,
    enum: EnumSetupPosition,
  })
  @IsEnum(EnumSetupPosition)
  @IsOptional()
  @Field(() => EnumSetupPosition, {
    nullable: true,
  })
  position?: "long" | "short" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousEntryValue?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousEntryValueEnd?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTaking1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTaking2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTaking3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTakingAmount1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTakingAmount2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTakingAmount3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousStopValue?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTaking1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTaking2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTaking3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTakingAmount1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTakingAmount2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTakingAmount3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rValue?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  report?: ReportCreateNestedManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: () => SetupValueHistoryCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => SetupValueHistoryCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => SetupValueHistoryCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  setupValueHistory?: SetupValueHistoryCreateNestedManyWithoutSetupsInput;

  @ApiProperty({
    required: true,
    enum: EnumSetupStatus,
  })
  @IsEnum(EnumSetupStatus)
  @Field(() => EnumSetupStatus)
  status!:
    | "incoming"
    | "active"
    | "cancelled"
    | "stopped"
    | "success"
    | "closed";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  stopDate?: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stopDistance?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stopValue?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subStatus?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  tags!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  targetDate?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tp1Date?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tp2Date?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tp3Date?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  trader?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TraderSetupPnlPerformanceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TraderSetupPnlPerformanceWhereUniqueInput)
  @IsOptional()
  @Field(() => TraderSetupPnlPerformanceWhereUniqueInput, {
    nullable: true,
  })
  traderSetupPnlPerformance?: TraderSetupPnlPerformanceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  updatedById?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserNotificationCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => UserNotificationCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => UserNotificationCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  userNotification?: UserNotificationCreateNestedManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: () => WatchListCreateNestedManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => WatchListCreateNestedManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => WatchListCreateNestedManyWithoutSetupsInput, {
    nullable: true,
  })
  watchList?: WatchListCreateNestedManyWithoutSetupsInput;
}

export { SetupCreateInput as SetupCreateInput };
