/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Setup } from "./Setup";
import { SetupCountArgs } from "./SetupCountArgs";
import { SetupFindManyArgs } from "./SetupFindManyArgs";
import { SetupFindUniqueArgs } from "./SetupFindUniqueArgs";
import { CreateSetupArgs } from "./CreateSetupArgs";
import { UpdateSetupArgs } from "./UpdateSetupArgs";
import { DeleteSetupArgs } from "./DeleteSetupArgs";
import { ClapFindManyArgs } from "../../clap/base/ClapFindManyArgs";
import { Clap } from "../../clap/base/Clap";
import { CopyTradeOrderFindManyArgs } from "../../copyTradeOrder/base/CopyTradeOrderFindManyArgs";
import { CopyTradeOrder } from "../../copyTradeOrder/base/CopyTradeOrder";
import { CopyTradeFindManyArgs } from "../../copyTrade/base/CopyTradeFindManyArgs";
import { CopyTrade } from "../../copyTrade/base/CopyTrade";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { SetupValueHistoryFindManyArgs } from "../../setupValueHistory/base/SetupValueHistoryFindManyArgs";
import { SetupValueHistory } from "../../setupValueHistory/base/SetupValueHistory";
import { UserNotificationFindManyArgs } from "../../userNotification/base/UserNotificationFindManyArgs";
import { UserNotification } from "../../userNotification/base/UserNotification";
import { WatchListFindManyArgs } from "../../watchList/base/WatchListFindManyArgs";
import { WatchList } from "../../watchList/base/WatchList";
import { User } from "../../user/base/User";
import { TraderSetupPnlPerformance } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformance";
import { SetupService } from "../setup.service";
@graphql.Resolver(() => Setup)
export class SetupResolverBase {
  constructor(protected readonly service: SetupService) {}

  async _setupsMeta(
    @graphql.Args() args: SetupCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Setup])
  async setups(@graphql.Args() args: SetupFindManyArgs): Promise<Setup[]> {
    return this.service.setups(args);
  }

  @graphql.Query(() => Setup, { nullable: true })
  async setup(
    @graphql.Args() args: SetupFindUniqueArgs
  ): Promise<Setup | null> {
    const result = await this.service.setup(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Setup)
  async createSetup(@graphql.Args() args: CreateSetupArgs): Promise<Setup> {
    return await this.service.createSetup({
      ...args,
      data: {
        ...args.data,

        trader: args.data.trader
          ? {
              connect: args.data.trader,
            }
          : undefined,

        traderSetupPnlPerformance: args.data.traderSetupPnlPerformance
          ? {
              connect: args.data.traderSetupPnlPerformance,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Setup)
  async updateSetup(
    @graphql.Args() args: UpdateSetupArgs
  ): Promise<Setup | null> {
    try {
      return await this.service.updateSetup({
        ...args,
        data: {
          ...args.data,

          trader: args.data.trader
            ? {
                connect: args.data.trader,
              }
            : undefined,

          traderSetupPnlPerformance: args.data.traderSetupPnlPerformance
            ? {
                connect: args.data.traderSetupPnlPerformance,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Setup)
  async deleteSetup(
    @graphql.Args() args: DeleteSetupArgs
  ): Promise<Setup | null> {
    try {
      return await this.service.deleteSetup(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Clap], { name: "clap" })
  async findClap(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: ClapFindManyArgs
  ): Promise<Clap[]> {
    const results = await this.service.findClap(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [CopyTradeOrder], { name: "copyTradeOrder" })
  async findCopyTradeOrder(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: CopyTradeOrderFindManyArgs
  ): Promise<CopyTradeOrder[]> {
    const results = await this.service.findCopyTradeOrder(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [CopyTrade], { name: "copyTrades" })
  async findCopyTrades(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: CopyTradeFindManyArgs
  ): Promise<CopyTrade[]> {
    const results = await this.service.findCopyTrades(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Report], { name: "report" })
  async findReport(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: ReportFindManyArgs
  ): Promise<Report[]> {
    const results = await this.service.findReport(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [SetupValueHistory], {
    name: "setupValueHistory",
  })
  async findSetupValueHistory(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: SetupValueHistoryFindManyArgs
  ): Promise<SetupValueHistory[]> {
    const results = await this.service.findSetupValueHistory(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [UserNotification], { name: "userNotification" })
  async findUserNotification(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: UserNotificationFindManyArgs
  ): Promise<UserNotification[]> {
    const results = await this.service.findUserNotification(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [WatchList], { name: "watchList" })
  async findWatchList(
    @graphql.Parent() parent: Setup,
    @graphql.Args() args: WatchListFindManyArgs
  ): Promise<WatchList[]> {
    const results = await this.service.findWatchList(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "trader",
  })
  async getTrader(@graphql.Parent() parent: Setup): Promise<User | null> {
    const result = await this.service.getTrader(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => TraderSetupPnlPerformance, {
    nullable: true,
    name: "traderSetupPnlPerformance",
  })
  async getTraderSetupPnlPerformance(
    @graphql.Parent() parent: Setup
  ): Promise<TraderSetupPnlPerformance | null> {
    const result = await this.service.getTraderSetupPnlPerformance(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
