/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Max,
  IsOptional,
  IsDate,
  IsEnum,
  ValidateNested,
  IsInt,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";

import { Type } from "class-transformer";
import { EnumSetupCategory } from "./EnumSetupCategory";
import { ClapUpdateManyWithoutSetupsInput } from "./ClapUpdateManyWithoutSetupsInput";
import { CopyTradeOrderUpdateManyWithoutSetupsInput } from "./CopyTradeOrderUpdateManyWithoutSetupsInput";
import { CopyTradeUpdateManyWithoutSetupsInput } from "./CopyTradeUpdateManyWithoutSetupsInput";
import { EnumSetupDuration } from "./EnumSetupDuration";
import { EnumSetupPosition } from "./EnumSetupPosition";
import { ReportUpdateManyWithoutSetupsInput } from "./ReportUpdateManyWithoutSetupsInput";
import { SetupValueHistoryUpdateManyWithoutSetupsInput } from "./SetupValueHistoryUpdateManyWithoutSetupsInput";
import { EnumSetupStatus } from "./EnumSetupStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { TraderSetupPnlPerformanceWhereUniqueInput } from "../../traderSetupPnlPerformance/base/TraderSetupPnlPerformanceWhereUniqueInput";
import { UserNotificationUpdateManyWithoutSetupsInput } from "./UserNotificationUpdateManyWithoutSetupsInput";
import { WatchListUpdateManyWithoutSetupsInput } from "./WatchListUpdateManyWithoutSetupsInput";

@InputType()
class SetupUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  activatedStopValue?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  activationDate?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumSetupCategory,
  })
  @IsEnum(EnumSetupCategory)
  @IsOptional()
  @Field(() => EnumSetupCategory, {
    nullable: true,
  })
  category?: "spot" | "futures";

  @ApiProperty({
    required: false,
    type: () => ClapUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => ClapUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => ClapUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  clap?: ClapUpdateManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  clapCount?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  closeDate?: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  closePrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  closedById?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  coinName?: string;

  @ApiProperty({
    required: false,
    type: () => CopyTradeOrderUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeOrderUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => CopyTradeOrderUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  copyTradeOrder?: CopyTradeOrderUpdateManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: () => CopyTradeUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => CopyTradeUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => CopyTradeUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  copyTrades?: CopyTradeUpdateManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdById?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSetupDuration,
  })
  @IsEnum(EnumSetupDuration)
  @IsOptional()
  @Field(() => EnumSetupDuration, {
    nullable: true,
  })
  duration?: "shortterm" | "midterm" | "longterm" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  entryValue?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  entryValueEnd?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageSuccess?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialEntryValue?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialEntryValueEnd?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTaking1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTaking2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTaking3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTakingAmount1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTakingAmount2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialProfitTakingAmount3?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  initialRr?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  initialStopValue?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isDeleted?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isHidden?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isStop?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTargeted?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTp1?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTp2?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTp3?: boolean | null;

  @ApiProperty({
    required: false,
    enum: EnumSetupPosition,
  })
  @IsEnum(EnumSetupPosition)
  @IsOptional()
  @Field(() => EnumSetupPosition, {
    nullable: true,
  })
  position?: "long" | "short" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousEntryValue?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousEntryValueEnd?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTaking1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTaking2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTaking3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTakingAmount1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTakingAmount2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousProfitTakingAmount3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  previousStopValue?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTaking1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTaking2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTaking3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTakingAmount1?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTakingAmount2?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  profitTakingAmount3?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rValue?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  report?: ReportUpdateManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: () => SetupValueHistoryUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => SetupValueHistoryUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => SetupValueHistoryUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  setupValueHistory?: SetupValueHistoryUpdateManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    enum: EnumSetupStatus,
  })
  @IsEnum(EnumSetupStatus)
  @IsOptional()
  @Field(() => EnumSetupStatus, {
    nullable: true,
  })
  status?:
    | "incoming"
    | "active"
    | "cancelled"
    | "stopped"
    | "success"
    | "closed";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  stopDate?: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stopDistance?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stopValue?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subStatus?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tags?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  targetDate?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tp1Date?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tp2Date?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tp3Date?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  trader?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TraderSetupPnlPerformanceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TraderSetupPnlPerformanceWhereUniqueInput)
  @IsOptional()
  @Field(() => TraderSetupPnlPerformanceWhereUniqueInput, {
    nullable: true,
  })
  traderSetupPnlPerformance?: TraderSetupPnlPerformanceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  updatedById?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserNotificationUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => UserNotificationUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => UserNotificationUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  userNotification?: UserNotificationUpdateManyWithoutSetupsInput;

  @ApiProperty({
    required: false,
    type: () => WatchListUpdateManyWithoutSetupsInput,
  })
  @ValidateNested()
  @Type(() => WatchListUpdateManyWithoutSetupsInput)
  @IsOptional()
  @Field(() => WatchListUpdateManyWithoutSetupsInput, {
    nullable: true,
  })
  watchList?: WatchListUpdateManyWithoutSetupsInput;
}

export { SetupUpdateInput as SetupUpdateInput };
