/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SetupService } from "../setup.service";
import { SetupCreateInput } from "./SetupCreateInput";
import { Setup } from "./Setup";
import { SetupFindManyArgs } from "./SetupFindManyArgs";
import { SetupWhereUniqueInput } from "./SetupWhereUniqueInput";
import { SetupUpdateInput } from "./SetupUpdateInput";
import { ClapFindManyArgs } from "../../clap/base/ClapFindManyArgs";
import { Clap } from "../../clap/base/Clap";
import { ClapWhereUniqueInput } from "../../clap/base/ClapWhereUniqueInput";
import { CopyTradeOrderFindManyArgs } from "../../copyTradeOrder/base/CopyTradeOrderFindManyArgs";
import { CopyTradeOrder } from "../../copyTradeOrder/base/CopyTradeOrder";
import { CopyTradeOrderWhereUniqueInput } from "../../copyTradeOrder/base/CopyTradeOrderWhereUniqueInput";
import { CopyTradeFindManyArgs } from "../../copyTrade/base/CopyTradeFindManyArgs";
import { CopyTrade } from "../../copyTrade/base/CopyTrade";
import { CopyTradeWhereUniqueInput } from "../../copyTrade/base/CopyTradeWhereUniqueInput";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { ReportWhereUniqueInput } from "../../report/base/ReportWhereUniqueInput";
import { SetupValueHistoryFindManyArgs } from "../../setupValueHistory/base/SetupValueHistoryFindManyArgs";
import { SetupValueHistory } from "../../setupValueHistory/base/SetupValueHistory";
import { SetupValueHistoryWhereUniqueInput } from "../../setupValueHistory/base/SetupValueHistoryWhereUniqueInput";
import { UserNotificationFindManyArgs } from "../../userNotification/base/UserNotificationFindManyArgs";
import { UserNotification } from "../../userNotification/base/UserNotification";
import { UserNotificationWhereUniqueInput } from "../../userNotification/base/UserNotificationWhereUniqueInput";
import { WatchListFindManyArgs } from "../../watchList/base/WatchListFindManyArgs";
import { WatchList } from "../../watchList/base/WatchList";
import { WatchListWhereUniqueInput } from "../../watchList/base/WatchListWhereUniqueInput";

export class SetupControllerBase {
  constructor(protected readonly service: SetupService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Setup })
  async createSetup(@common.Body() data: SetupCreateInput): Promise<Setup> {
    return await this.service.createSetup({
      data: {
        ...data,

        trader: data.trader
          ? {
              connect: data.trader,
            }
          : undefined,

        traderSetupPnlPerformance: data.traderSetupPnlPerformance
          ? {
              connect: data.traderSetupPnlPerformance,
            }
          : undefined,
      },
      select: {
        activatedStopValue: true,
        activationDate: true,
        category: true,
        clapCount: true,
        closeDate: true,
        closePrice: true,
        closedById: true,
        coinName: true,
        createdAt: true,
        createdById: true,
        duration: true,
        entryValue: true,
        entryValueEnd: true,
        id: true,
        image: true,
        imageSuccess: true,
        initialEntryValue: true,
        initialEntryValueEnd: true,
        initialProfitTaking1: true,
        initialProfitTaking2: true,
        initialProfitTaking3: true,
        initialProfitTakingAmount1: true,
        initialProfitTakingAmount2: true,
        initialProfitTakingAmount3: true,
        initialRr: true,
        initialStopValue: true,
        isActive: true,
        isDeleted: true,
        isHidden: true,
        isStop: true,
        isTargeted: true,
        isTp1: true,
        isTp2: true,
        isTp3: true,
        position: true,
        previousEntryValue: true,
        previousEntryValueEnd: true,
        previousProfitTaking1: true,
        previousProfitTaking2: true,
        previousProfitTaking3: true,
        previousProfitTakingAmount1: true,
        previousProfitTakingAmount2: true,
        previousProfitTakingAmount3: true,
        previousStopValue: true,
        profitTaking1: true,
        profitTaking2: true,
        profitTaking3: true,
        profitTakingAmount1: true,
        profitTakingAmount2: true,
        profitTakingAmount3: true,
        rValue: true,
        status: true,
        stopDate: true,
        stopDistance: true,
        stopValue: true,
        subStatus: true,
        tags: true,
        targetDate: true,
        tp1Date: true,
        tp2Date: true,
        tp3Date: true,

        trader: {
          select: {
            id: true,
          },
        },

        traderSetupPnlPerformance: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Setup] })
  @ApiNestedQuery(SetupFindManyArgs)
  async setups(@common.Req() request: Request): Promise<Setup[]> {
    const args = plainToClass(SetupFindManyArgs, request.query);
    return this.service.setups({
      ...args,
      select: {
        activatedStopValue: true,
        activationDate: true,
        category: true,
        clapCount: true,
        closeDate: true,
        closePrice: true,
        closedById: true,
        coinName: true,
        createdAt: true,
        createdById: true,
        duration: true,
        entryValue: true,
        entryValueEnd: true,
        id: true,
        image: true,
        imageSuccess: true,
        initialEntryValue: true,
        initialEntryValueEnd: true,
        initialProfitTaking1: true,
        initialProfitTaking2: true,
        initialProfitTaking3: true,
        initialProfitTakingAmount1: true,
        initialProfitTakingAmount2: true,
        initialProfitTakingAmount3: true,
        initialRr: true,
        initialStopValue: true,
        isActive: true,
        isDeleted: true,
        isHidden: true,
        isStop: true,
        isTargeted: true,
        isTp1: true,
        isTp2: true,
        isTp3: true,
        position: true,
        previousEntryValue: true,
        previousEntryValueEnd: true,
        previousProfitTaking1: true,
        previousProfitTaking2: true,
        previousProfitTaking3: true,
        previousProfitTakingAmount1: true,
        previousProfitTakingAmount2: true,
        previousProfitTakingAmount3: true,
        previousStopValue: true,
        profitTaking1: true,
        profitTaking2: true,
        profitTaking3: true,
        profitTakingAmount1: true,
        profitTakingAmount2: true,
        profitTakingAmount3: true,
        rValue: true,
        status: true,
        stopDate: true,
        stopDistance: true,
        stopValue: true,
        subStatus: true,
        tags: true,
        targetDate: true,
        tp1Date: true,
        tp2Date: true,
        tp3Date: true,

        trader: {
          select: {
            id: true,
          },
        },

        traderSetupPnlPerformance: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Setup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async setup(
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<Setup | null> {
    const result = await this.service.setup({
      where: params,
      select: {
        activatedStopValue: true,
        activationDate: true,
        category: true,
        clapCount: true,
        closeDate: true,
        closePrice: true,
        closedById: true,
        coinName: true,
        createdAt: true,
        createdById: true,
        duration: true,
        entryValue: true,
        entryValueEnd: true,
        id: true,
        image: true,
        imageSuccess: true,
        initialEntryValue: true,
        initialEntryValueEnd: true,
        initialProfitTaking1: true,
        initialProfitTaking2: true,
        initialProfitTaking3: true,
        initialProfitTakingAmount1: true,
        initialProfitTakingAmount2: true,
        initialProfitTakingAmount3: true,
        initialRr: true,
        initialStopValue: true,
        isActive: true,
        isDeleted: true,
        isHidden: true,
        isStop: true,
        isTargeted: true,
        isTp1: true,
        isTp2: true,
        isTp3: true,
        position: true,
        previousEntryValue: true,
        previousEntryValueEnd: true,
        previousProfitTaking1: true,
        previousProfitTaking2: true,
        previousProfitTaking3: true,
        previousProfitTakingAmount1: true,
        previousProfitTakingAmount2: true,
        previousProfitTakingAmount3: true,
        previousStopValue: true,
        profitTaking1: true,
        profitTaking2: true,
        profitTaking3: true,
        profitTakingAmount1: true,
        profitTakingAmount2: true,
        profitTakingAmount3: true,
        rValue: true,
        status: true,
        stopDate: true,
        stopDistance: true,
        stopValue: true,
        subStatus: true,
        tags: true,
        targetDate: true,
        tp1Date: true,
        tp2Date: true,
        tp3Date: true,

        trader: {
          select: {
            id: true,
          },
        },

        traderSetupPnlPerformance: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Setup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSetup(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() data: SetupUpdateInput
  ): Promise<Setup | null> {
    try {
      return await this.service.updateSetup({
        where: params,
        data: {
          ...data,

          trader: data.trader
            ? {
                connect: data.trader,
              }
            : undefined,

          traderSetupPnlPerformance: data.traderSetupPnlPerformance
            ? {
                connect: data.traderSetupPnlPerformance,
              }
            : undefined,
        },
        select: {
          activatedStopValue: true,
          activationDate: true,
          category: true,
          clapCount: true,
          closeDate: true,
          closePrice: true,
          closedById: true,
          coinName: true,
          createdAt: true,
          createdById: true,
          duration: true,
          entryValue: true,
          entryValueEnd: true,
          id: true,
          image: true,
          imageSuccess: true,
          initialEntryValue: true,
          initialEntryValueEnd: true,
          initialProfitTaking1: true,
          initialProfitTaking2: true,
          initialProfitTaking3: true,
          initialProfitTakingAmount1: true,
          initialProfitTakingAmount2: true,
          initialProfitTakingAmount3: true,
          initialRr: true,
          initialStopValue: true,
          isActive: true,
          isDeleted: true,
          isHidden: true,
          isStop: true,
          isTargeted: true,
          isTp1: true,
          isTp2: true,
          isTp3: true,
          position: true,
          previousEntryValue: true,
          previousEntryValueEnd: true,
          previousProfitTaking1: true,
          previousProfitTaking2: true,
          previousProfitTaking3: true,
          previousProfitTakingAmount1: true,
          previousProfitTakingAmount2: true,
          previousProfitTakingAmount3: true,
          previousStopValue: true,
          profitTaking1: true,
          profitTaking2: true,
          profitTaking3: true,
          profitTakingAmount1: true,
          profitTakingAmount2: true,
          profitTakingAmount3: true,
          rValue: true,
          status: true,
          stopDate: true,
          stopDistance: true,
          stopValue: true,
          subStatus: true,
          tags: true,
          targetDate: true,
          tp1Date: true,
          tp2Date: true,
          tp3Date: true,

          trader: {
            select: {
              id: true,
            },
          },

          traderSetupPnlPerformance: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Setup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSetup(
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<Setup | null> {
    try {
      return await this.service.deleteSetup({
        where: params,
        select: {
          activatedStopValue: true,
          activationDate: true,
          category: true,
          clapCount: true,
          closeDate: true,
          closePrice: true,
          closedById: true,
          coinName: true,
          createdAt: true,
          createdById: true,
          duration: true,
          entryValue: true,
          entryValueEnd: true,
          id: true,
          image: true,
          imageSuccess: true,
          initialEntryValue: true,
          initialEntryValueEnd: true,
          initialProfitTaking1: true,
          initialProfitTaking2: true,
          initialProfitTaking3: true,
          initialProfitTakingAmount1: true,
          initialProfitTakingAmount2: true,
          initialProfitTakingAmount3: true,
          initialRr: true,
          initialStopValue: true,
          isActive: true,
          isDeleted: true,
          isHidden: true,
          isStop: true,
          isTargeted: true,
          isTp1: true,
          isTp2: true,
          isTp3: true,
          position: true,
          previousEntryValue: true,
          previousEntryValueEnd: true,
          previousProfitTaking1: true,
          previousProfitTaking2: true,
          previousProfitTaking3: true,
          previousProfitTakingAmount1: true,
          previousProfitTakingAmount2: true,
          previousProfitTakingAmount3: true,
          previousStopValue: true,
          profitTaking1: true,
          profitTaking2: true,
          profitTaking3: true,
          profitTakingAmount1: true,
          profitTakingAmount2: true,
          profitTakingAmount3: true,
          rValue: true,
          status: true,
          stopDate: true,
          stopDistance: true,
          stopValue: true,
          subStatus: true,
          tags: true,
          targetDate: true,
          tp1Date: true,
          tp2Date: true,
          tp3Date: true,

          trader: {
            select: {
              id: true,
            },
          },

          traderSetupPnlPerformance: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updatedById: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/clap")
  @ApiNestedQuery(ClapFindManyArgs)
  async findClap(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<Clap[]> {
    const query = plainToClass(ClapFindManyArgs, request.query);
    const results = await this.service.findClap(params.id, {
      ...query,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/clap")
  async connectClap(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: ClapWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clap: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/clap")
  async updateClap(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: ClapWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clap: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/clap")
  async disconnectClap(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: ClapWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clap: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/copyTradeOrder")
  @ApiNestedQuery(CopyTradeOrderFindManyArgs)
  async findCopyTradeOrder(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<CopyTradeOrder[]> {
    const query = plainToClass(CopyTradeOrderFindManyArgs, request.query);
    const results = await this.service.findCopyTradeOrder(params.id, {
      ...query,
      select: {
        actPx: true,
        actSz: true,

        copyTrades: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        percentage: true,
        requestPx: true,
        requestSz: true,
        requestedAt: true,

        setup: {
          select: {
            id: true,
          },
        },

        side: true,
        status: true,
        statusAt: true,
        statusMessage: true,
        stopLossPx: true,
        takeProfitPx: true,
        tpValue: true,
        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/copyTradeOrder")
  async connectCopyTradeOrder(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: CopyTradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradeOrder: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/copyTradeOrder")
  async updateCopyTradeOrder(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: CopyTradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradeOrder: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/copyTradeOrder")
  async disconnectCopyTradeOrder(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: CopyTradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTradeOrder: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/copyTrades")
  @ApiNestedQuery(CopyTradeFindManyArgs)
  async findCopyTrades(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<CopyTrade[]> {
    const query = plainToClass(CopyTradeFindManyArgs, request.query);
    const results = await this.service.findCopyTrades(params.id, {
      ...query,
      select: {
        activatedAt: true,
        assetSize: true,
        copiedAt: true,
        createdAt: true,
        createdById: true,
        errorMessage: true,
        errorNo: true,
        id: true,
        isDeleted: true,
        market: true,
        realizedPnl: true,
        realizedR: true,

        setup: {
          select: {
            id: true,
          },
        },

        state: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,
        usdSize: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/copyTrades")
  async connectCopyTrades(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTrades: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/copyTrades")
  async updateCopyTrades(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTrades: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/copyTrades")
  async disconnectCopyTrades(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: CopyTradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      copyTrades: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/report")
  @ApiNestedQuery(ReportFindManyArgs)
  async findReport(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<Report[]> {
    const query = plainToClass(ReportFindManyArgs, request.query);
    const results = await this.service.findReport(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/report")
  async connectReport(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      report: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/report")
  async updateReport(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      report: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/report")
  async disconnectReport(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      report: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/setupValueHistory")
  @ApiNestedQuery(SetupValueHistoryFindManyArgs)
  async findSetupValueHistory(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<SetupValueHistory[]> {
    const query = plainToClass(SetupValueHistoryFindManyArgs, request.query);
    const results = await this.service.findSetupValueHistory(params.id, {
      ...query,
      select: {
        createdAt: true,
        fieldField: true,
        id: true,

        setup: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/setupValueHistory")
  async connectSetupValueHistory(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: SetupValueHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      setupValueHistory: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/setupValueHistory")
  async updateSetupValueHistory(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: SetupValueHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      setupValueHistory: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/setupValueHistory")
  async disconnectSetupValueHistory(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: SetupValueHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      setupValueHistory: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userNotification")
  @ApiNestedQuery(UserNotificationFindManyArgs)
  async findUserNotification(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<UserNotification[]> {
    const query = plainToClass(UserNotificationFindManyArgs, request.query);
    const results = await this.service.findUserNotification(params.id, {
      ...query,
      select: {
        columnValue: true,
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,
        isRead: true,
        message: true,
        messageId: true,

        setup: {
          select: {
            id: true,
          },
        },

        trader: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
        updatedById: true,
        updatedColumn: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userNotification")
  async connectUserNotification(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotification: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userNotification")
  async updateUserNotification(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotification: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userNotification")
  async disconnectUserNotification(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: UserNotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userNotification: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/watchList")
  @ApiNestedQuery(WatchListFindManyArgs)
  async findWatchList(
    @common.Req() request: Request,
    @common.Param() params: SetupWhereUniqueInput
  ): Promise<WatchList[]> {
    const query = plainToClass(WatchListFindManyArgs, request.query);
    const results = await this.service.findWatchList(params.id, {
      ...query,
      select: {
        createdAt: true,
        createdById: true,
        id: true,
        isDeleted: true,

        setup: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updatedById: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/watchList")
  async connectWatchList(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: WatchListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      watchList: {
        connect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/watchList")
  async updateWatchList(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: WatchListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      watchList: {
        set: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/watchList")
  async disconnectWatchList(
    @common.Param() params: SetupWhereUniqueInput,
    @common.Body() body: WatchListWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      watchList: {
        disconnect: body,
      },
    };
    await this.service.updateSetup({
      where: params,
      data,
      select: { id: true },
    });
  }
}
