import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CalendarTextListRelationFilter } from "../calendarText/CalendarTextListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntFilter } from "../../util/IntFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";

export type CalendarWhereInput = {
  acroExpand?: StringNullableFilter;
  actual?: StringNullableFilter;
  alsoCalled?: StringNullableFilter;
  calendarText?: CalendarTextListRelationFilter;
  ccNotes?: StringNullableFilter;
  ccNotice?: StringNullableFilter;
  country?: StringNullableFilter;
  countryCode?: StringNullableFilter;
  createdAt?: DateTimeNullableFilter;
  createdById?: StringNullableFilter;
  dataEcobaseid?: IntFilter;
  dataEventId?: IntFilter;
  date?: DateTimeNullableFilter;
  derivedVia?: StringNullableFilter;
  description?: StringNullableFilter;
  eventDatetime?: DateTimeNullableFilter;
  forecast?: StringNullableFilter;
  frequency?: StringNullableFilter;
  id?: StringFilter;
  impact?: StringNullableFilter;
  isDeleted?: BooleanFilter;
  measures?: StringNullableFilter;
  nextRelease?: StringNullableFilter;
  previous?: StringNullableFilter;
  source?: StringNullableFilter;
  speaker?: StringNullableFilter;
  time?: StringNullableFilter;
  title?: StringNullableFilter;
  updatedAt?: DateTimeNullableFilter;
  updatedById?: StringNullableFilter;
  usualEffect?: StringNullableFilter;
  whyTraderscare?: StringNullableFilter;
};
