import { ClapUpdateManyWithoutUsersInput } from "./ClapUpdateManyWithoutUsersInput";
import { CopyTradeOrderUpdateManyWithoutUsersInput } from "./CopyTradeOrderUpdateManyWithoutUsersInput";
import { CopyTradeUpdateManyWithoutUsersInput } from "./CopyTradeUpdateManyWithoutUsersInput";
import { FollowNotifyUpdateManyWithoutUsersInput } from "./FollowNotifyUpdateManyWithoutUsersInput";
import { ReferralCodeUpdateManyWithoutUsersInput } from "./ReferralCodeUpdateManyWithoutUsersInput";
import { ReferralCodeWhereUniqueInput } from "../referralCode/ReferralCodeWhereUniqueInput";
import { ReportUpdateManyWithoutUsersInput } from "./ReportUpdateManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { SessionUpdateManyWithoutUsersInput } from "./SessionUpdateManyWithoutUsersInput";
import { SetupUpdateManyWithoutUsersInput } from "./SetupUpdateManyWithoutUsersInput";
import { TeamTraderUpdateManyWithoutUsersInput } from "./TeamTraderUpdateManyWithoutUsersInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { TraderProfileWhereUniqueInput } from "../traderProfile/TraderProfileWhereUniqueInput";
import { TraderReferralEarningUpdateManyWithoutUsersInput } from "./TraderReferralEarningUpdateManyWithoutUsersInput";
import { TraderSetupPnlPerformanceUpdateManyWithoutUsersInput } from "./TraderSetupPnlPerformanceUpdateManyWithoutUsersInput";
import { TraderStatWhereUniqueInput } from "../traderStat/TraderStatWhereUniqueInput";
import { TraderSuspensionWhereUniqueInput } from "../traderSuspension/TraderSuspensionWhereUniqueInput";
import { UserNotificationUpdateManyWithoutUsersInput } from "./UserNotificationUpdateManyWithoutUsersInput";
import { UserSubscriptionUpdateManyWithoutUsersInput } from "./UserSubscriptionUpdateManyWithoutUsersInput";
import { WatchListUpdateManyWithoutUsersInput } from "./WatchListUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  approvedAt?: Date | null;
  canCopyTrade?: boolean;
  clap?: ClapUpdateManyWithoutUsersInput;
  copyTradeConnected?: boolean;
  copyTradeMarket?: string | null;
  copyTradeMarketUid?: string | null;
  copyTradeOrder?: CopyTradeOrderUpdateManyWithoutUsersInput;
  copyTradesCopyTradesTraderIdTouser?: CopyTradeUpdateManyWithoutUsersInput;
  copyTradesCopyTradesUserIdTouser?: CopyTradeUpdateManyWithoutUsersInput;
  createdById?: string | null;
  deviceId?: string | null;
  email?: string | null;
  emailValidationCode?: string | null;
  firstName?: string | null;
  followNotifyFollowNotifyTraderIdTouser?: FollowNotifyUpdateManyWithoutUsersInput;
  followNotifyFollowNotifyUserIdTouser?: FollowNotifyUpdateManyWithoutUsersInput;
  image?: string | null;
  instagram?: string | null;
  isActive?: boolean;
  isAdmin?: boolean;
  isApproved?: boolean;
  isChangePassword?: boolean;
  isCopyNotify?: boolean;
  isCustomer?: boolean;
  isDeleted?: boolean;
  isEmailVerified?: boolean;
  isMembershipCompleted?: boolean;
  isNotify?: boolean;
  isTrader?: boolean;
  isTrending?: boolean;
  language?: string | null;
  lastName?: string | null;
  monthlyR?: number | null;
  monthlyRoi?: string | null;
  name?: string | null;
  password?: string | null;
  phone?: string | null;
  rate?: number | null;
  referralCodeReferralCodeTraderIdTouser?: ReferralCodeUpdateManyWithoutUsersInput;
  referralCodeUserReferralCodeIdToreferralCode?: ReferralCodeWhereUniqueInput | null;
  registrationToken?: string | null;
  reportReportTraderIdTouser?: ReportUpdateManyWithoutUsersInput;
  reportReportUserIdTouser?: ReportUpdateManyWithoutUsersInput;
  roles?: InputJsonValue;
  sessions?: SessionUpdateManyWithoutUsersInput;
  setup?: SetupUpdateManyWithoutUsersInput;
  suspensionStartDate?: Date | null;
  teamTraders?: TeamTraderUpdateManyWithoutUsersInput;
  teams?: TeamWhereUniqueInput | null;
  telegram?: string | null;
  traderProfile?: TraderProfileWhereUniqueInput | null;
  traderReferralEarning?: TraderReferralEarningUpdateManyWithoutUsersInput;
  traderSetupPnlPerformance?: TraderSetupPnlPerformanceUpdateManyWithoutUsersInput;
  traderStats?: TraderStatWhereUniqueInput | null;
  traderSuspension?: TraderSuspensionWhereUniqueInput | null;
  twitter?: string | null;
  uid?: string | null;
  updatedAt?: Date | null;
  updatedById?: string | null;
  userNotificationUserNotificationTraderIdTouser?: UserNotificationUpdateManyWithoutUsersInput;
  userNotifications?: UserNotificationUpdateManyWithoutUsersInput;
  userSubscriptionUserSubscriptionTraderIdTouser?: UserSubscriptionUpdateManyWithoutUsersInput;
  userSubscriptions?: UserSubscriptionUpdateManyWithoutUsersInput;
  username?: string | null;
  watchList?: WatchListUpdateManyWithoutUsersInput;
};
