import { Clap } from "../clap/Clap";
import { CopyTradeOrder } from "../copyTradeOrder/CopyTradeOrder";
import { CopyTrade } from "../copyTrade/CopyTrade";
import { FollowNotify } from "../followNotify/FollowNotify";
import { ReferralCode } from "../referralCode/ReferralCode";
import { Report } from "../report/Report";
import { JsonValue } from "type-fest";
import { Session } from "../session/Session";
import { Setup } from "../setup/Setup";
import { TeamTrader } from "../teamTrader/TeamTrader";
import { Team } from "../team/Team";
import { TraderProfile } from "../traderProfile/TraderProfile";
import { TraderReferralEarning } from "../traderReferralEarning/TraderReferralEarning";
import { TraderSetupPnlPerformance } from "../traderSetupPnlPerformance/TraderSetupPnlPerformance";
import { TraderStat } from "../traderStat/TraderStat";
import { TraderSuspension } from "../traderSuspension/TraderSuspension";
import { UserNotification } from "../userNotification/UserNotification";
import { UserSubscription } from "../userSubscription/UserSubscription";
import { WatchList } from "../watchList/WatchList";

export type User = {
  approvedAt: Date | null;
  canCopyTrade: boolean;
  clap?: Array<Clap>;
  copyTradeConnected: boolean;
  copyTradeMarket: string | null;
  copyTradeMarketUid: string | null;
  copyTradeOrder?: Array<CopyTradeOrder>;
  copyTradesCopyTradesTraderIdTouser?: Array<CopyTrade>;
  copyTradesCopyTradesUserIdTouser?: Array<CopyTrade>;
  createdAt: Date | null;
  createdById: string | null;
  deviceId: string | null;
  email: string | null;
  emailValidationCode: string | null;
  firstName: string | null;
  followNotifyFollowNotifyTraderIdTouser?: Array<FollowNotify>;
  followNotifyFollowNotifyUserIdTouser?: Array<FollowNotify>;
  id: string;
  image: string | null;
  instagram: string | null;
  isActive: boolean;
  isAdmin: boolean;
  isApproved: boolean;
  isChangePassword: boolean;
  isCopyNotify: boolean;
  isCustomer: boolean;
  isDeleted: boolean;
  isEmailVerified: boolean;
  isMembershipCompleted: boolean;
  isNotify: boolean;
  isTrader: boolean;
  isTrending: boolean;
  language: string | null;
  lastName: string | null;
  monthlyR: number | null;
  monthlyRoi: string | null;
  name: string | null;
  password: string | null;
  phone: string | null;
  rate: number | null;
  referralCodeReferralCodeTraderIdTouser?: Array<ReferralCode>;
  referralCodeUserReferralCodeIdToreferralCode?: ReferralCode | null;
  registrationToken: string | null;
  reportReportTraderIdTouser?: Array<Report>;
  reportReportUserIdTouser?: Array<Report>;
  roles: JsonValue;
  sessions?: Array<Session>;
  setup?: Array<Setup>;
  suspensionStartDate: Date | null;
  teamTraders?: Array<TeamTrader>;
  teams?: Team | null;
  telegram: string | null;
  traderProfile?: TraderProfile | null;
  traderReferralEarning?: Array<TraderReferralEarning>;
  traderSetupPnlPerformance?: Array<TraderSetupPnlPerformance>;
  traderStats?: TraderStat | null;
  traderSuspension?: TraderSuspension | null;
  twitter: string | null;
  uid: string | null;
  updatedAt: Date | null;
  updatedById: string | null;
  userNotificationUserNotificationTraderIdTouser?: Array<UserNotification>;
  userNotifications?: Array<UserNotification>;
  userSubscriptionUserSubscriptionTraderIdTouser?: Array<UserSubscription>;
  userSubscriptions?: Array<UserSubscription>;
  username: string | null;
  watchList?: Array<WatchList>;
};
