import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { ClapListRelationFilter } from "../clap/ClapListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CopyTradeOrderListRelationFilter } from "../copyTradeOrder/CopyTradeOrderListRelationFilter";
import { CopyTradeListRelationFilter } from "../copyTrade/CopyTradeListRelationFilter";
import { FollowNotifyListRelationFilter } from "../followNotify/FollowNotifyListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ReferralCodeListRelationFilter } from "../referralCode/ReferralCodeListRelationFilter";
import { ReferralCodeWhereUniqueInput } from "../referralCode/ReferralCodeWhereUniqueInput";
import { ReportListRelationFilter } from "../report/ReportListRelationFilter";
import { SessionListRelationFilter } from "../session/SessionListRelationFilter";
import { SetupListRelationFilter } from "../setup/SetupListRelationFilter";
import { TeamTraderListRelationFilter } from "../teamTrader/TeamTraderListRelationFilter";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { TraderProfileWhereUniqueInput } from "../traderProfile/TraderProfileWhereUniqueInput";
import { TraderReferralEarningListRelationFilter } from "../traderReferralEarning/TraderReferralEarningListRelationFilter";
import { TraderSetupPnlPerformanceListRelationFilter } from "../traderSetupPnlPerformance/TraderSetupPnlPerformanceListRelationFilter";
import { TraderStatWhereUniqueInput } from "../traderStat/TraderStatWhereUniqueInput";
import { TraderSuspensionWhereUniqueInput } from "../traderSuspension/TraderSuspensionWhereUniqueInput";
import { UserNotificationListRelationFilter } from "../userNotification/UserNotificationListRelationFilter";
import { UserSubscriptionListRelationFilter } from "../userSubscription/UserSubscriptionListRelationFilter";
import { WatchListListRelationFilter } from "../watchList/WatchListListRelationFilter";

export type UserWhereInput = {
  approvedAt?: DateTimeNullableFilter;
  canCopyTrade?: BooleanFilter;
  clap?: ClapListRelationFilter;
  copyTradeConnected?: BooleanFilter;
  copyTradeMarket?: StringNullableFilter;
  copyTradeMarketUid?: StringNullableFilter;
  copyTradeOrder?: CopyTradeOrderListRelationFilter;
  copyTradesCopyTradesTraderIdTouser?: CopyTradeListRelationFilter;
  copyTradesCopyTradesUserIdTouser?: CopyTradeListRelationFilter;
  createdAt?: DateTimeNullableFilter;
  createdById?: StringNullableFilter;
  deviceId?: StringNullableFilter;
  email?: StringNullableFilter;
  emailValidationCode?: StringNullableFilter;
  firstName?: StringNullableFilter;
  followNotifyFollowNotifyTraderIdTouser?: FollowNotifyListRelationFilter;
  followNotifyFollowNotifyUserIdTouser?: FollowNotifyListRelationFilter;
  id?: StringFilter;
  image?: StringNullableFilter;
  instagram?: StringNullableFilter;
  isActive?: BooleanFilter;
  isAdmin?: BooleanFilter;
  isApproved?: BooleanFilter;
  isChangePassword?: BooleanFilter;
  isCopyNotify?: BooleanFilter;
  isCustomer?: BooleanFilter;
  isDeleted?: BooleanFilter;
  isEmailVerified?: BooleanFilter;
  isMembershipCompleted?: BooleanFilter;
  isNotify?: BooleanFilter;
  isTrader?: BooleanFilter;
  isTrending?: BooleanFilter;
  language?: StringNullableFilter;
  lastName?: StringNullableFilter;
  monthlyR?: IntNullableFilter;
  monthlyRoi?: StringNullableFilter;
  name?: StringNullableFilter;
  password?: StringNullableFilter;
  phone?: StringNullableFilter;
  rate?: IntNullableFilter;
  referralCodeReferralCodeTraderIdTouser?: ReferralCodeListRelationFilter;
  referralCodeUserReferralCodeIdToreferralCode?: ReferralCodeWhereUniqueInput;
  registrationToken?: StringNullableFilter;
  reportReportTraderIdTouser?: ReportListRelationFilter;
  reportReportUserIdTouser?: ReportListRelationFilter;
  sessions?: SessionListRelationFilter;
  setup?: SetupListRelationFilter;
  suspensionStartDate?: DateTimeNullableFilter;
  teamTraders?: TeamTraderListRelationFilter;
  teams?: TeamWhereUniqueInput;
  telegram?: StringNullableFilter;
  traderProfile?: TraderProfileWhereUniqueInput;
  traderReferralEarning?: TraderReferralEarningListRelationFilter;
  traderSetupPnlPerformance?: TraderSetupPnlPerformanceListRelationFilter;
  traderStats?: TraderStatWhereUniqueInput;
  traderSuspension?: TraderSuspensionWhereUniqueInput;
  twitter?: StringNullableFilter;
  uid?: StringNullableFilter;
  updatedAt?: DateTimeNullableFilter;
  updatedById?: StringNullableFilter;
  userNotificationUserNotificationTraderIdTouser?: UserNotificationListRelationFilter;
  userNotifications?: UserNotificationListRelationFilter;
  userSubscriptionUserSubscriptionTraderIdTouser?: UserSubscriptionListRelationFilter;
  userSubscriptions?: UserSubscriptionListRelationFilter;
  username?: StringNullableFilter;
  watchList?: WatchListListRelationFilter;
};
