import { ClapCreateNestedManyWithoutUsersInput } from "./ClapCreateNestedManyWithoutUsersInput";
import { CopyTradeOrderCreateNestedManyWithoutUsersInput } from "./CopyTradeOrderCreateNestedManyWithoutUsersInput";
import { CopyTradeCreateNestedManyWithoutUsersInput } from "./CopyTradeCreateNestedManyWithoutUsersInput";
import { FollowNotifyCreateNestedManyWithoutUsersInput } from "./FollowNotifyCreateNestedManyWithoutUsersInput";
import { ReferralCodeCreateNestedManyWithoutUsersInput } from "./ReferralCodeCreateNestedManyWithoutUsersInput";
import { ReferralCodeWhereUniqueInput } from "../referralCode/ReferralCodeWhereUniqueInput";
import { ReportCreateNestedManyWithoutUsersInput } from "./ReportCreateNestedManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { SessionCreateNestedManyWithoutUsersInput } from "./SessionCreateNestedManyWithoutUsersInput";
import { SetupCreateNestedManyWithoutUsersInput } from "./SetupCreateNestedManyWithoutUsersInput";
import { TeamTraderCreateNestedManyWithoutUsersInput } from "./TeamTraderCreateNestedManyWithoutUsersInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { TraderProfileWhereUniqueInput } from "../traderProfile/TraderProfileWhereUniqueInput";
import { TraderReferralEarningCreateNestedManyWithoutUsersInput } from "./TraderReferralEarningCreateNestedManyWithoutUsersInput";
import { TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput } from "./TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput";
import { TraderStatWhereUniqueInput } from "../traderStat/TraderStatWhereUniqueInput";
import { TraderSuspensionWhereUniqueInput } from "../traderSuspension/TraderSuspensionWhereUniqueInput";
import { UserNotificationCreateNestedManyWithoutUsersInput } from "./UserNotificationCreateNestedManyWithoutUsersInput";
import { UserSubscriptionCreateNestedManyWithoutUsersInput } from "./UserSubscriptionCreateNestedManyWithoutUsersInput";
import { WatchListCreateNestedManyWithoutUsersInput } from "./WatchListCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  approvedAt?: Date | null;
  canCopyTrade: boolean;
  clap?: ClapCreateNestedManyWithoutUsersInput;
  copyTradeConnected: boolean;
  copyTradeMarket?: string | null;
  copyTradeMarketUid?: string | null;
  copyTradeOrder?: CopyTradeOrderCreateNestedManyWithoutUsersInput;
  copyTradesCopyTradesTraderIdTouser?: CopyTradeCreateNestedManyWithoutUsersInput;
  copyTradesCopyTradesUserIdTouser?: CopyTradeCreateNestedManyWithoutUsersInput;
  createdById?: string | null;
  deviceId?: string | null;
  email?: string | null;
  emailValidationCode?: string | null;
  firstName?: string | null;
  followNotifyFollowNotifyTraderIdTouser?: FollowNotifyCreateNestedManyWithoutUsersInput;
  followNotifyFollowNotifyUserIdTouser?: FollowNotifyCreateNestedManyWithoutUsersInput;
  image?: string | null;
  instagram?: string | null;
  isActive: boolean;
  isAdmin: boolean;
  isApproved: boolean;
  isChangePassword: boolean;
  isCopyNotify: boolean;
  isCustomer: boolean;
  isDeleted: boolean;
  isEmailVerified: boolean;
  isMembershipCompleted: boolean;
  isNotify: boolean;
  isTrader: boolean;
  isTrending: boolean;
  language?: string | null;
  lastName?: string | null;
  monthlyR?: number | null;
  monthlyRoi?: string | null;
  name?: string | null;
  password?: string | null;
  phone?: string | null;
  rate?: number | null;
  referralCodeReferralCodeTraderIdTouser?: ReferralCodeCreateNestedManyWithoutUsersInput;
  referralCodeUserReferralCodeIdToreferralCode?: ReferralCodeWhereUniqueInput | null;
  registrationToken?: string | null;
  reportReportTraderIdTouser?: ReportCreateNestedManyWithoutUsersInput;
  reportReportUserIdTouser?: ReportCreateNestedManyWithoutUsersInput;
  roles: InputJsonValue;
  sessions?: SessionCreateNestedManyWithoutUsersInput;
  setup?: SetupCreateNestedManyWithoutUsersInput;
  suspensionStartDate?: Date | null;
  teamTraders?: TeamTraderCreateNestedManyWithoutUsersInput;
  teams?: TeamWhereUniqueInput | null;
  telegram?: string | null;
  traderProfile?: TraderProfileWhereUniqueInput | null;
  traderReferralEarning?: TraderReferralEarningCreateNestedManyWithoutUsersInput;
  traderSetupPnlPerformance?: TraderSetupPnlPerformanceCreateNestedManyWithoutUsersInput;
  traderStats?: TraderStatWhereUniqueInput | null;
  traderSuspension?: TraderSuspensionWhereUniqueInput | null;
  twitter?: string | null;
  uid?: string | null;
  updatedAt?: Date | null;
  updatedById?: string | null;
  userNotificationUserNotificationTraderIdTouser?: UserNotificationCreateNestedManyWithoutUsersInput;
  userNotifications?: UserNotificationCreateNestedManyWithoutUsersInput;
  userSubscriptionUserSubscriptionTraderIdTouser?: UserSubscriptionCreateNestedManyWithoutUsersInput;
  userSubscriptions?: UserSubscriptionCreateNestedManyWithoutUsersInput;
  username?: string | null;
  watchList?: WatchListCreateNestedManyWithoutUsersInput;
};
