/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SubscriptionPool } from "./SubscriptionPool";
import { SubscriptionPoolCountArgs } from "./SubscriptionPoolCountArgs";
import { SubscriptionPoolFindManyArgs } from "./SubscriptionPoolFindManyArgs";
import { SubscriptionPoolFindUniqueArgs } from "./SubscriptionPoolFindUniqueArgs";
import { CreateSubscriptionPoolArgs } from "./CreateSubscriptionPoolArgs";
import { UpdateSubscriptionPoolArgs } from "./UpdateSubscriptionPoolArgs";
import { DeleteSubscriptionPoolArgs } from "./DeleteSubscriptionPoolArgs";
import { UserSubscription } from "../../userSubscription/base/UserSubscription";
import { SubscriptionPoolService } from "../subscriptionPool.service";
@graphql.Resolver(() => SubscriptionPool)
export class SubscriptionPoolResolverBase {
  constructor(protected readonly service: SubscriptionPoolService) {}

  async _subscriptionPoolsMeta(
    @graphql.Args() args: SubscriptionPoolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SubscriptionPool])
  async subscriptionPools(
    @graphql.Args() args: SubscriptionPoolFindManyArgs
  ): Promise<SubscriptionPool[]> {
    return this.service.subscriptionPools(args);
  }

  @graphql.Query(() => SubscriptionPool, { nullable: true })
  async subscriptionPool(
    @graphql.Args() args: SubscriptionPoolFindUniqueArgs
  ): Promise<SubscriptionPool | null> {
    const result = await this.service.subscriptionPool(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SubscriptionPool)
  async createSubscriptionPool(
    @graphql.Args() args: CreateSubscriptionPoolArgs
  ): Promise<SubscriptionPool> {
    return await this.service.createSubscriptionPool({
      ...args,
      data: {
        ...args.data,

        userSubscription: args.data.userSubscription
          ? {
              connect: args.data.userSubscription,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SubscriptionPool)
  async updateSubscriptionPool(
    @graphql.Args() args: UpdateSubscriptionPoolArgs
  ): Promise<SubscriptionPool | null> {
    try {
      return await this.service.updateSubscriptionPool({
        ...args,
        data: {
          ...args.data,

          userSubscription: args.data.userSubscription
            ? {
                connect: args.data.userSubscription,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SubscriptionPool)
  async deleteSubscriptionPool(
    @graphql.Args() args: DeleteSubscriptionPoolArgs
  ): Promise<SubscriptionPool | null> {
    try {
      return await this.service.deleteSubscriptionPool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => UserSubscription, {
    nullable: true,
    name: "userSubscription",
  })
  async getUserSubscription(
    @graphql.Parent() parent: SubscriptionPool
  ): Promise<UserSubscription | null> {
    const result = await this.service.getUserSubscription(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
