/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  SubscriptionPool as PrismaSubscriptionPool,
  UserSubscription as PrismaUserSubscription,
} from "@prisma/client";

export class SubscriptionPoolServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SubscriptionPoolCountArgs, "select">
  ): Promise<number> {
    return this.prisma.subscriptionPool.count(args);
  }

  async subscriptionPools(
    args: Prisma.SubscriptionPoolFindManyArgs
  ): Promise<PrismaSubscriptionPool[]> {
    return this.prisma.subscriptionPool.findMany(args);
  }
  async subscriptionPool(
    args: Prisma.SubscriptionPoolFindUniqueArgs
  ): Promise<PrismaSubscriptionPool | null> {
    return this.prisma.subscriptionPool.findUnique(args);
  }
  async createSubscriptionPool(
    args: Prisma.SubscriptionPoolCreateArgs
  ): Promise<PrismaSubscriptionPool> {
    return this.prisma.subscriptionPool.create(args);
  }
  async updateSubscriptionPool(
    args: Prisma.SubscriptionPoolUpdateArgs
  ): Promise<PrismaSubscriptionPool> {
    return this.prisma.subscriptionPool.update(args);
  }
  async deleteSubscriptionPool(
    args: Prisma.SubscriptionPoolDeleteArgs
  ): Promise<PrismaSubscriptionPool> {
    return this.prisma.subscriptionPool.delete(args);
  }

  async getUserSubscription(
    parentId: string
  ): Promise<PrismaUserSubscription | null> {
    return this.prisma.subscriptionPool
      .findUnique({
        where: { id: parentId },
      })
      .userSubscription();
  }
}
